### ISSUE TITLE
Error 502 Bad Gateway

### ISSUE THREAD

**Issue by cebasfu93** [processing/p5.js-web-editor#850] opened 2019-02-28 19:19 UTC
#### Nature of issue?

- Unable to download sketch.

#### Details about the bug: 

- Web browser and version: Firefox 65.0 and Chrome 72.0.3626.119 
- Operating System: Windows 10
- Steps to reproduce this bug: On the sketch's page: File -> Download. A new window is opened trying to download the sketch. It fails with "Error 502: Bad gateway". I have tried other sketches and browsers with no success.

![image](https://user-images.githubusercontent.com/12839647/53592204-1251e180-3b96-11e9-9469-d62a64839755.png)

**Comment by catarak** [comment] 2019-02-28 19:21
thanks for reporting! this is working for me on Mac so maybe it's a Windows issue. will investigate!

**Comment by catarak** [comment] 2019-03-01 20:17
just tried this on Windows 10 Firefox/Chrome, and I'm not able to reproduce. i think that when you tried to download, there must have been an issue with the hosting. i'm going to close this for now, feel free to reopen if this comes up again!

**Comment by slowizzm** [comment] 2019-03-12 23:52
Currently getting this error, sure everyone is aware, just wanted to point it out.

**Comment by Dooskington** [comment] 2019-05-02 18:09
I'm also getting this error all of a sudden.
Operating system is macOS, browser is Chrome. I've been trying it for a few days now, so I think it's safe to assume it isn't just a temporary hosting outage.

Unsure if it's related, but I didn't notice this behavior until after I replaced the default CDN version of p5 with my own uploaded version (packaged from the most recent code on master branch). Other than that, I've got a few images in the project as well.

@catarak Please re-open!

**Comment by catarak** [comment] 2019-05-02 18:31
@Dooskington i'm not able to reproduce... does this only occur on a specific sketch or anytime you try to visit the web editor? if the former, can you post a link to the specific sketch?

**Comment by Dooskington** [comment] 2019-05-02 22:29
@catarak 

Hey, seems to be happening on this specific sketch:
https://editor.p5js.org/declanho/sketches/WmbbIi4zs

**Comment by catarak** [comment] 2019-05-02 22:38
@Dooskington interesting! I'm able to load that page and run the sketch. have you tried in a private browsing window? do you have other steps to reproduce? i'm scratching my head on this one...

**Comment by Dooskington** [comment] 2019-05-02 22:51
@catarak You are able to run the sketch, or you are able to download it?
I can run it fine, but downloading it (from the file->download option) causes a 502 gateway error.

**Comment by catarak** [comment] 2019-05-02 22:51
oh! okay, let me try downloading it.

**Comment by catarak** [comment] 2019-05-02 23:12
okay, i am able to reproduce. i will reopen and investigate!

**Comment by catarak** [comment] 2019-05-02 23:33
i was able to figure out the bug and fix this! it will be deployed in ~10 min.

**Comment by cris-maillo** [comment] 2020-04-15 10:04
Hi, I'm also getting the same error, I'm using Windows 10 - and I've tried with both Chrome and Firefox. The bug seems to be also linked to the sketch, as my other projects can be downloaded.

https://editor.p5js.org/cris.maillo/sketches/eBs347EIo 
Thank you!

**Comment by catarak** [comment] 2020-04-15 21:39
@cris-maillo managed to figure out the cause! Merging a PR now.

**Closed** 2020-04-15 21:40 UTC
Labels: priority:medium, type:bug

**Comment by Typ0Codes** [comment] 2025-12-04 00:49
having this issue on windows 11. tried both chrome and fire fox https://editor.p5js.org/SLDTyp0/sketches/bOBmhjv1F

i am getting an error 502 which is same as OP
