### ISSUE TITLE
Error 400 with Google oAuth

### ISSUE THREAD

**Issue by rdurrance2021** [processing/p5.js-web-editor#1956] opened 2021-11-04 11:44 UTC
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Version 92.0.4515.131 (Official Build) (64-bit)
- Operating System: Windows 10 20H2
- Steps to reproduce this bug:
Logging in with Google oAuth gives error 400. Students cannot access their sketches
![p5_oAuth_Error](https://user-images.githubusercontent.com/93713017/140307824-06de8de0-b268-4528-9b1b-91d6c3118022.jpg)
:

**Comment by DavidGriswoldTeacher** [comment] 2021-11-04 12:01
This is a duplicate of #1946 , I described what I think is the solution there but it requires action from whoever has access to the P5JS Google Developer Console.

**Comment by DavidGriswoldTeacher** [comment] 2021-11-04 12:01
This is a duplicate of #1946  , I described what I think is the solution there but it requires action from whoever has access to the P5JS Google Developer Console.

**Comment by catarak** [comment] 2021-11-04 17:43
This has been fixed, and I'm sorry for not fixing this sooner. We're a really small team (in fact, the editor team is just me, part time), and there are a lot of notifications on discord/discourse/GitHub/Twitter/etc. It's difficult to sift through them and find that things that need to be attended to immediately. In the future, for anything urgent, please email hello@p5js.org. And also, in the future, I'll do a better job of communicating how to reach the team for urgent issues. I really appreciate the patience and support!

**Closed as completed by catarak** 2021-11-04 17:43 UTC
