### ISSUE TITLE
error in a loop

### ISSUE THREAD

**Issue by garryson361** [processing/p5.js-web-editor#461] opened 2017-10-25 15:54 UTC
When I run the code below (on my account), I get the error:
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'. (sketch: line 45)
I have tried not being on my account and when I log off, the error doesn't happen
code:
var x = 600
var speed = 1
function setup() { 
  createCanvas(400, 400);
} 

function draw() { 
  var time = Math.round(x / 0.6) / 100
  var fuse = x / 10
  background(220);
  rect(x,10,1,1)
  text(time,10,10)
    fill(255,10,10)
  for(var i = 0;i < 5; i++){
    rect(180,180,10,100)
  }
  for(var j = 0; j < fuse ;j++){
   rect(184,178 - j / 1,2,2) 
  }
  x = x - speed
}
there is probably a simple fix but I can't find it

**Comment by MathuraMG** [comment] 2017-10-25 20:22
@catarak - I think this may have to do with the accessibility outputs.
@garryson361 - do you by any chance have any accessibility option checked in the preferences?

**Comment by garryson361** [comment] 2017-10-25 22:00
Yes I do.

**Comment by MathuraMG** [comment] 2017-10-25 22:22
Please could you verify if the error goes away if you uncheck Plain-text?

**Comment by garryson361** [comment] 2017-10-26 03:04
Yes. It does.

**Comment by catarak** [comment] 2017-10-26 17:40
@MathuraMG thanks for figuring out the cause of this issue!

**Comment by catarak** [comment] 2017-11-13 20:29
This was fixed with https://github.com/MathuraMG/p5-interceptor/pull/8

**Closed by catarak** 2017-11-13 20:29 UTC
