### ISSUE TITLE
Automatic logout happens too easily.

### ISSUE THREAD

**Issue by golanlevin** [processing/p5.js-web-editor#259] opened 2017-01-07 22:06 UTC
It seems very easy to get logged out by accident.

**Comment by catarak** [comment] 2017-01-08 22:07
hmmm, which browser are you using?

**Comment by catarak** [comment] 2017-05-24 17:38
i'm not able to reproduce this so i'm going to close this issue. feel free to reopen if this comes up again!

**Closed by catarak** 2017-05-24 17:38 UTC
Labels: priority:low, type:bug
