### ISSUE TITLE
Bug: link is not bold or hover effect on Keyboard Shortcuts page

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [processing/p5.js-web-editor#2959] opened 2024-01-26 20:37 UTC
### What is your operating system?

Windows

### Web browser and version

Chrome

### Actual Behavior

normal text color and link text color are the same. it can't be understood properly.

<img width="341" alt="Screenshot 2024-01-27 014933" src="https://github.com/processing/p5.js-web-editor/assets/69814563/b98c474e-ae42-46ab-aa47-c442bbdacde7">

### Expected Behavior

The text should be bold and have hover effects.

### Steps:

- [x] open site.
- [x] Click the `Help` button above
- [x] then click `Keyboard Shortcuts`
```

**Comment by lindapaiste** [comment] 2024-01-26 22:42
closing as a duplicate of #2940.  see #2947 for further discussion.

**Closed as not planned by lindapaiste** 2024-01-26 22:42 UTC
Labels: Bug
