### ISSUE TITLE
List of user sketches visibility (public or private) - education

### ISSUE THREAD

**Issue by Wildernesss** [processing/p5.js-web-editor#1604] opened 2020-09-05 11:02 UTC
#### Nature of issue

- Existing feature enhancement

#### Feature enhancement details:

Hi everyone. I've just discoverd that in p5.js editor when ones clicks on username on the right of sketch name, just after the 'by' (for example 'hello world' by superman) ones gets the list of all user sketches and collections, and so can access all of them. That's very nice to explore p5.js and discover examples + ideas of sketches.

But, unfortunately there is a but, for a teacher using p5.js editor with his/her students, that's very embarrassing from an educational point of view. I give my students exercices as sketches templates to complete  (they duplicate them and then make their exercices on their own from that point, adding their code). And I've also on p5.js editor all solutions of my exercices. So, that means that if one my students click on my username in my templates exercices, she/he has got access to the solution of all exercices and can simply make a copy/paste of solutions code and then give me back her completed exercice, without having learnt anything.

More generally, it would be great if, for each sketch, user would have the choice for a public visibility of her/his sketch or not. Public sketches would appear into the list of visible sketch of user, non public would be only available only to people having the link.

It should not be a too big work to add such a boolean field into sketches DB and adjust the SQL request returning the list of public user sketches.

Thanks for your attention and great work :o)

Laurent

**Comment by catarak** [comment] 2020-09-09 16:35
Thanks for the suggestion! I hear you and this is a priority near-term for the web editor. More soon 😄 I'm going to close this issue as it is a duplicate of #91. 

In the very near term, the way that folks have gotten around this is by creating multiple accounts, one containing templates and one containing solutions. I know it's not ideal but I hope to have this feature implemented soon!

**Closed as completed by catarak** 2020-09-09 16:35 UTC
