### ISSUE TITLE
Web Editor 'Open' button keeps crashing.

### ISSUE THREAD

**Issue by ananya32** [processing/p5.js-web-editor#1013] opened 2019-04-02 06:06 UTC
**### Can't open any previously saved files.**
Found a bug
Details about the bug:
Every time I click 'Open' the whole page just goes blank. Literally all blank white.

Chrome, Version 73.0.3683.86

Operating System: MacOS Mojave version 10.14.3

Steps to reproduce this bug: Every time I log in to my account and click 'Open' the whole page just goes blank. Literally all blank white.

I lost a lot of my homework that I had already done due to this. I'd really appreciate it if anyone knows how I could recover my files.

I've attached screenshots below of what happens everytime I click on 'Open' -
<img width="1440" alt="Screenshot 2019-04-01 at 7 46 20 AM" src="https://user-images.githubusercontent.com/48466636/55379620-abed1580-54eb-11e9-91e3-0a47801aeaaa.png">
<img width="1440" alt="Screenshot 2019-04-01 at 7 46 09 AM" src="https://user-images.githubusercontent.com/48466636/55379621-abed1580-54eb-11e9-8ac3-b87aa7d830b2.png">

**Comment by catarak** [comment] 2019-04-03 17:34
thanks for reporting! closing this as a duplicate of #1012.

**Closed by catarak** 2019-04-03 17:34 UTC
