### ISSUE TITLE
Sketches not sortable in My Collections Page

### ISSUE THREAD

**Issue by haarsh157** [processing/p5.js-web-editor#2900] opened 2024-01-15 14:19 UTC
### What is your operating system?

None

### Actual Behavior

When clicking on table headers, the sketches did not get sorted.

https://github.com/processing/p5.js-web-editor/assets/115213858/344ced75-5a4c-44de-87b0-9b2a9afbb3d8

### Expected Behavior

The sketches should be sorted when we click on the table headers.

### Steps:
1. Navigate to the collections by selecting File -> Open -> Collections. Ensure that you are logged in and have created collections.
2. Execute table sorting by clicking on the headers to align the table accordingly.

**Comment by KrishavRajSingh** [comment] 2024-01-15 14:23
Bro I have worked on this
Checkout #2732

**Comment by lindapaiste** [comment] 2024-01-15 18:16
Closing as a duplicate of #2375

**Closed as not planned by lindapaiste** 2024-01-15 18:16 UTC
Labels: Bug
