### ISSUE TITLE
`Console` warning: Failed prop type when clicking on `Add to collection` on latest develop

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2715] opened 2023-12-13 06:33 UTC
### p5.js version

2.10.0

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

`Console` warning: Failed prop type when clicking on `Add to collection` on latest develop

### Expected Behavior

There should be no console warning

### Steps:
1. Open the editor web app
2. Click on my sketches
3. Click on add to collection from the dropdown menu
4. Notice the console warning

**Comment by aryanas159** [comment] 2023-12-13 11:09
This error occurs when there are no collections, one potential solution could be to send an alert message "Please create a collection first". Can I work on this?

**Comment by lindapaiste** [comment] 2023-12-13 17:34
Can you please paste the exact text of the error?  I have seen prop-types errors when I have a collection which contains deleted items.

**Comment by aryanas159** [comment] 2023-12-13 17:58
@lindapaiste 
![image](https://github.com/processing/p5.js-web-editor/assets/114330931/80a10b79-15ae-4bdd-8bec-b2564a85ef9c)
The error isn't visible in the production environment.

**Comment by lindapaiste** [comment] 2023-12-13 21:18
> The error isn't visible in the production environment.

Prop-types errors are always shown in development only.

That warning doesn't seem like it's due to having no collections. An empty array would still meet all of the conditions enforced by the prop types.

It's due to one or more `collections` containing one or more `items` which don't match the required `ItemsShape`.  Specifically, the bad item(s) don't have a `.project.createdAt` property.  We don't ever examine that property so it should be removed from the prop types.  In general, we should only specify the properties which are actually needed.

But I don't know if we need a new PR because it will be fixed by #2353 which removes all of the props.

**Comment by lindapaiste** [comment] 2023-12-13 21:22
Closing as a duplicate of #2351

**Closed as not planned by lindapaiste** 2023-12-13 21:22 UTC
Labels: Bug, Area: Code Quality
