### ISSUE TITLE
Signup Section is not aligned properly.

### ISSUE THREAD

**Issue by rahulrana701** [processing/p5.js-web-editor#2989] opened 2024-02-04 19:51 UTC
### p5.js version

1.9.0

### What is your operating system?

Windows

### Web browser and version

chrome://121.0.6167.85

### Actual Behavior

The signup form is not properly aligned as login form.
this is the login form and this is how signup form should be aligned 
<img width="958" alt="Screenshot 2024-02-05 011207" src="https://github.com/processing/p5.js-web-editor/assets/123585591/777f789f-6188-4821-b0d7-f6d19c1e6919">
but signup page is not like that , we need to put some extra spacing above 
<img width="960" alt="Screenshot 2024-02-05 011225" src="https://github.com/processing/p5.js-web-editor/assets/123585591/ffd45dad-0632-4d4f-92b6-0113251343fc">

### Expected Behavior

signup form should look like this 
<img width="955" alt="Screenshot 2024-02-05 011331" src="https://github.com/processing/p5.js-web-editor/assets/123585591/8c9492c1-1b30-41e4-9090-4e226a38c67e">

### Steps:
1. Go to SignUp Section

**Comment by rahulrana701** [comment] 2024-02-04 19:51
@lindapaiste I would like to work on it

**Comment by Keshav-0907** [comment] 2024-02-04 20:51
@rahulrana701, I don't think it's a bug. The `form-container` is vertically centered and introducing padding will lead to UI disruption on various screen sizes. 

Moreover, the current version also ensures that the majority of the content is visible to the user.

**Comment by lindapaiste** [comment] 2024-02-04 21:38
> @rahulrana701, I don't think it's a bug. The `form-container` is vertically centered and introducing padding will lead to UI disruption on various screen sizes.
> 
> Moreover, the current version also ensures that the majority of the content is visible to the user.

Yeah, it's not a bug that the two titles are in different places.  That is by design.  The content is centered vertically on the screen.

I can possibly see the argument that the title is close to the top on screens with a small height.  In that case we would want to add some sort of margin or padding which is equal on both the top and the bottom so that things stay centered.  It would serve as the minimum top spacing for screens with a height of < ~730px.  But we need to be aware that any blank space which we add on top will cause more text on the bottom to be hidden off-screen.

**Comment by rahulrana701** [comment] 2024-02-05 03:11
@lindapaiste i will fix that by today

**Comment by raclim** [comment] 2024-03-27 20:56
Thanks for reporting this! 

I think in light of some other issues we probably won't implement this for now, especially since this was originally part of the UI. I'm going to close this issue and its affiliated PR, but I'm also down to revisit this down the line if other folks see this as an issue or would like to explore more in-depth design changes for this page.

**Closed as not planned by raclim** 2024-03-27 20:56 UTC
Labels: Bug
