### ISSUE TITLE
Opening and closing of the Redux DevTools using `ctrl+h` not working in mWeb(safari) and mWeb(chrome) 

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2504] opened 2023-10-15 07:48 UTC
### p5.js version

2.7.3

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

Opening and closing of the Redux DevTools using `ctrl+h` not working in mWeb(safari) and mWeb(chrome) 

https://github.com/processing/p5.js-web-editor/assets/47579287/dada0277-edf4-4cec-8621-703b7faca5e2

### Expected Behavior

Opening and closing of the Redux DevTools using `ctrl+h` should work in mWeb(safari) and mWeb(chrome) as `ctrl+w` is working - it is moving them

### Steps:
1. Open p5.js web app in mobile either in mWeb(safari) or mWeb(chrome)
2. Press `ctrl+h`, nothing happens - It should hide the redux devTools
3. Press `ctrl+w` , working as intended - It is moving the redux devTools

**Comment by ayeshag7** [comment] 2023-12-16 08:21
Hi, I couldn't reproduce this error on my web browser. `ctrl+h` seems to be working correctly by opening and closing the Redux dev tools. Is this error only occurring on mobile phone screens? Thanks!

**Closed as not planned** 2024-08-13 16:29 UTC
Labels: Bug
