### ISSUE TITLE
innerHTML error on random lines

### ISSUE THREAD

**Issue by FriddoDK** [processing/p5.js-web-editor#326] opened 2017-03-24 13:56 UTC
after experimenting with a simple collider script, i ran into this error that occurred while in play mode and testing.

here's the script link: 
http://alpha.editor.p5js.org/MemeMeister420/sketches/S16FaKbne
(i know! silly name!)

it delivers this message in the console saying;
Uncaught TypeError: Cannot set property 'innerHTML' of undefined (sketch: line 19)
on random lines and there dosen't seem to be any reason.

it's quite annoying that the program stops in the middle of a play and you have to start it again,

some specs:
CPU: i5-6600K
RAM: 16gb 2133mhz
Browser: Chrome version 56.0.2924.87 (64-bit)

**Comment by catarak** [comment] 2017-03-25 19:20
I'm unfortunately not able to reproduce this. Can you give me a little more context as to how you seem to be triggering it? Also, just to be safe--try running the sketch in an incognito window to make sure you don't have any chrome extensions that are messing with it.

**Comment by FriddoDK** [comment] 2017-03-28 14:59
at the time of writing this reply, it seams to be gone.
but im not sure.

**Comment by catarak** [comment] 2017-03-28 17:02
no worries! i'm going to close this for now, but feel free to reopen this issue if you're able to reproduce it.

**Closed by catarak** 2017-03-28 17:02 UTC

**Comment by FriddoDK** [comment] 2017-04-03 09:33
Will do
