### ISSUE TITLE
p5.js editor console with weird behavior on mutable types

### ISSUE THREAD

**Issue by ScriptHosT12** [processing/p5.js-web-editor#1055] opened 2019-04-17 21:08 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (editor)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 0.7.3
- Web browser and version: Chrome 73.0.3683.103
- Operating System: Windows 7 
- Steps to reproduce this:
Create and run this code
```
function a(){
  var v = []
  console.log(v);
  v.push(1);
  console.log(v);
  v.pop();
}
```
On the chrome dev tools it logs `[]` and `[1]`, but on p5.js console it logs twice a blank array

**Comment by AnkurIngale** [comment] 2019-04-29 14:09
A recent commit in the editor squashed all similar consecutive console messages. I'll find that commit but I feel that might be the reason for such behaviour.

**Comment by catarak** [comment] 2019-04-30 20:11
thanks for reporting! i am able to reproduce. this seems to be an error specifically with the web editor and how it handles console messages.

**Comment by ashu8912** [comment] 2020-02-01 18:28
This is no error with web editor its an error in the "console-feed" library tha we are using , 
even codesandbox that is using the same library has this issue.

**Comment by catarak** [comment] 2020-03-24 20:21
Seems like this is the same underlying issue as #1203.

**Comment by catarak** [comment] 2021-02-10 21:49
Going to close this into #1203.

**Closed by catarak** 2021-02-10 21:49 UTC
Labels: priority:high, type:bug
