### ISSUE TITLE
No Spacing.

### ISSUE THREAD

**Issue by branhost** [processing/p5.js-web-editor#343] opened 2017-04-21 10:23 UTC
In the p5.js [web editor](https://alpha.editor.p5js.org/) there is an annoying bug. If I type something and try to go back to add spaces for changes it deletes the code! Please fix this soon. Thanks!

**Comment by catarak** [comment] 2017-04-21 16:01
Which browser are you using? There are some lingering issues with Microsoft Edge.

**Comment by catarak** [comment] 2017-05-10 20:22
@branhost can you add more details, such as the browser and OS you are using so that I can try to reproduce?

**Comment by catarak** [comment] 2017-05-24 16:18
i'm not able to reproduce this so i'm going to close this issue. feel free to reopen this if you have steps to reproduce or you run into this issue again.

**Closed** 2017-05-24 16:18 UTC
Labels: can't reproduce
