### ISSUE TITLE
unable to add a file to a folder

### ISSUE THREAD

**Issue by yzeal** [processing/p5.js-web-editor#1173] opened 2019-10-02 18:06 UTC
#### Nature of issue?

- Found a bug (?)

#### Details about the bug: 

- Web browser and version: Firefox 69.0.1 and Chrome 77.0.3865.90 (64-Bit)
- Operating System: Microsoft Windows 10 Pro (Version 10.0.17763 Build 17763)

- Steps to reproduce this bug:

I'm trying to add an image file to a folder I've created using the Web Editor. But instead of appearing inside the folder, the new image is placed outside of it.

I've made a video of the issue using Firefox, but the same happens in Chrome: https://youtu.be/XJAgZUVSads
It doesn't happen every time. 

I'm quite new to p5.js so I might be doing something wrong and this might not be a bug at all. Thank you for your time!

**Comment by catarak** [comment] 2019-10-03 18:36
thanks for reporting! this is actually a duplicate of #963. basically, you need to click on the folder first in order to add it to that folder. this is obviously not the expected behavior and therefore a bug.

**Closed by catarak** 2019-10-03 18:36 UTC
