### ISSUE TITLE
Language gets directly changes to English after login without any choice.

### ISSUE THREAD

**Issue by Vishal2002** [processing/p5.js-web-editor#2862] opened 2024-01-07 08:45 UTC
### p5.js version

v1.9.0

### What is your operating system?

Windows

### Web browser and version

120.0.6099.199

### Actual Behavior

**When we choose the language of choice and then try to log in with our credentials, the language automatically gets changed to the English language.**

_**Sample Video**_

https://drive.google.com/file/d/13ZEZU31UcSd2dJrU0Ar_LkC2XxfSQ68B/view?usp=sharing

### Expected Behavior

**The Language should still be one which was choosen  before login.**

### Steps:
1. Change the language from top
2. Login to your account
3. When you get into your account the language will automatically change to English without any choice.

**Comment by lindapaiste** [comment] 2024-01-07 18:45
Hmmm...I'm not sure if this is a problem or if it's doing what it's supposed to do?  When you log it will change to the language from your account preferences.  In your video that was English.

It does not always change to English when logging in -- it happens to do so in this example because English is the language that you were last using when you logged out.

Let's say that I'm logged in and I change my preferences to Spanish.  Then I log out and I change it to French.  Then I log in.  The language will be Spanish because that is the language associated with my account.

**Comment by YashwardhanSingh2005** [comment] 2024-01-08 09:43
I was reading about this issue and was thinking whether we would proceed with changing it so the language stays the same before login session rather than storing it as a language associated with the account?

**Comment by imsamad** [comment] 2024-01-08 11:36
> Hmmm...I'm not sure if this is a problem or if it's doing what it's supposed to do? When you log it will change to the language from your account preferences. In your video that was English.
> 
> It does not always change to English when logging in -- it happens to do so in this example because English is the language that you were last using when you logged out.
> 
> Let's say that I'm logged in and I change my preferences to Spanish. Then I log out and I change it to French. Then I log in. The language will be Spanish because that is the language associated with my account.

I think, it is not good from user-experience of non-technical user perspective. 

We can solve this issue as follows:

Saving the selected language preference in local storage when a user is logged out and then syncing that preference to the backend upon login.

If this approach is right, I am interested to work on it, please assign it to me.

**Comment by Vishal2002** [comment] 2024-01-08 12:04
@lindapaiste  I just need your confirmation to start working on this issue because I have already figured out how to do this.

**Comment by mhsh312** [comment] 2024-01-08 16:20
I agree with @lindapaiste. This works as intended. Languages should be tied to the last preference of a specific account. Multiple users can be using the same computer with different accounts (say, in a school computer lab) so keeping languages tied to account preferences is the way to go.

**Comment by raclim** [comment] 2024-01-26 16:36
I think that's how I'm feeling so far here as well. I'm not sure if this is something we might want to consider in the near future so I'm going to close this for now, but am down to reopen this if more interest in this issue resurfaces!

**Closed as not planned by raclim** 2024-01-26 16:36 UTC
Labels: Area: Translation, Bug
