### ISSUE TITLE
File items should be disappear when clicked anywhere on the window

### ISSUE THREAD

**Issue by PiyushThapaa** [processing/p5.js-web-editor#2998] opened 2024-02-07 10:15 UTC
### Increasing Access

It will get easier for users to close the file items

### Feature enhancement details

![Screenshot 2024-02-07 153647](https://github.com/processing/p5.js-web-editor/assets/112943430/8baa4155-16da-4008-aac8-e2c3387bfb5d)
The file items is closing only when we click on that plus mark which is kinda annoying
Instead we can make the file items close when clicked anywhere on the window 

@lindapaiste @raclim If you want this to be done please assign this to me...

**Comment by Rizil-Patel** [comment] 2024-02-07 13:19
Hello @lindapaiste 

I 'm a new contributor and I 'm interested in solving this issue.

Please assign me this issue ,I would also like to propose the solution for this issue.

**Comment by Keshav-0907** [comment] 2024-02-07 15:33
This issue is duplicate of #2524

**Closed as not planned** 2024-02-07 15:41 UTC
Labels: Enhancement
