### ISSUE TITLE
Purpose of folder file

### ISSUE THREAD

**Issue by nimishagarwal76** [processing/p5.js-web-editor#1032] opened 2019-04-13 11:34 UTC
#### Nature of issue?

- Found a bug

#### Details about the bug: 
I am not sure if this is an inteded feature since it is there from the begining, what is the purpose of the file that we get on clicking folder name. Generally it is expected upon clicking of the name folder should toggle its visibility of its contents but currently it happens only on clicking of the caret.

![Screenshot (3)](https://user-images.githubusercontent.com/37630020/56079134-d99c5d80-5e0d-11e9-92ac-0dcefffbcd72.png)

**Comment by anku255** [comment] 2019-04-16 06:27
Duplicate of #945

**Closed** 2019-04-16 06:55 UTC
