### ISSUE TITLE
Issue Logging in using Google

### ISSUE THREAD

**Issue by Mshuman8** [processing/p5.js-web-editor#1947] opened 2021-10-22 22:47 UTC
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome 95.0.4638.54 (and the one before it)
- Operating System: Mac; Mojave 10.14.5
- Steps to reproduce this bug: I try to login using Google and get an Authorization Error. This also happens for all of my students as well. If we try logging in somewhere between 3 and 6 times it generally will eventually log us in.

<img width="488" alt="Screen Shot 2021-10-22 at 6 41 42 PM" src="https://user-images.githubusercontent.com/37717052/138530876-584268e6-3c90-40aa-8292-f82110b95dca.png">

**Comment by code4humanity** [comment] 2021-10-24 16:25
Related to #1946

**Comment by DavidGriswoldTeacher** [comment] 2021-11-04 12:01
Duplicate of #1946 , I described what I think is the solution there but it requires action from whoever has access to the P5JS Google Developer Console.

**Comment by catarak** [comment] 2021-11-04 17:43
This has been fixed, and I'm sorry for not fixing this sooner. We're a really small team (in fact, the editor team is just me, part time), and there are a lot of notifications on discord/discourse/GitHub/Twitter/etc. It's difficult to sift through them and find that things that need to be attended to immediately. In the future, for anything urgent, please email hello@p5js.org. And also, in the future, I'll do a better job of communicating how to reach the team for urgent issues. I really appreciate the patience and support!

**Closed as completed by catarak** 2021-11-04 17:43 UTC

**Comment by Mshuman8** [comment] 2021-11-04 18:19
Hello!

Please do not apologize at all! I mainly just resubmitted because I had
gotten a few responses and thought it might have been marked as completed.
I am SO appreciative for your work and for you fixing it. I love love love
teaching p5 and use the editor daily!

I hope you have a wonderful day!

Marisa Shuman
