### ISSUE TITLE
There should be a confirmation before loggingout

### ISSUE THREAD

**Issue by PiyushThapaa** [processing/p5.js-web-editor#3005] opened 2024-02-08 05:50 UTC
### Increasing Access

It will prevent accidental logout by users

### Feature request details

Whenever a user who is already loggedin try to logout, a confirmation will come with a message `Are you sure you want to log out?` 
This will prevent accidental logouts..

@lindapaiste @raclim If you want this feature please assign this one to me...

**Comment by raclim** [comment] 2024-02-08 16:43
Thanks for opening this! This has already been reported, so I'm going to close this as a duplicate of #2492. There's a few PRs in queue for this already, but feel free to go ahead with working on this if you'd like!

**Closed as not planned by raclim** 2024-02-08 16:43 UTC
Labels: Feature Request
