### ISSUE TITLE
[bug]: Language of Terms and Policy remains same

### ISSUE THREAD

**Issue by Shyam-Raghuwanshi** [processing/p5.js-web-editor#2901] opened 2024-01-15 16:37 UTC
### What is your operating system?

None

### Actual Behavior

https://www.loom.com/share/13f7a5fe22f14d3a8fb9dca4779e653b?sid=984d487f-9eb9-4523-ba73-3cb7aade1107

the text - By signing up, you agree to the p5.js Editor's Terms of Service and Privacy Policy remains same

### Expected Behavior

it should be change dynamically

https://www.loom.com/share/2dc5e2df3a1e42a3b5017dc2fe2f73fb?sid=5120415d-cceb-413d-9395-631ff02cd00a

### Steps:
Go to the Signup page

**Comment by lindapaiste** [comment] 2024-01-15 18:17
Closing as a duplicate of #2871

**Closed as not planned by lindapaiste** 2024-01-15 18:17 UTC
Labels: Bug
