### ISSUE TITLE
print() breaks sketch

### ISSUE THREAD

**Issue by peterkvt80** [processing/p5.js-web-editor#743] opened 2018-10-25 13:27 UTC
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### (duplicate of bug 618) If you have an empty print() statement inside draw(), then it puts up a print dialog. If you dismiss it, then it will just put up another dialog and you can't get back to your sketch.

It is a problem if you happen to type in print() first before filling in the parameters. My workaround is to enter print statements as a comments, then uncomment it when ready.

I'd prefer it to ignore print() with undefined or missing parameters.

- Steps to reproduce this:
Putting print() inside draw() puts up the print dialog and it is impossible to exit from this.

function setup() {
}

function draw() {
  print()
}

**Comment by catarak** [comment] 2018-10-25 16:32
thanks for reporting! in p5, if you use `print()` with no arguments, it opens the print dialog. this is because `print()` is a feature of all browsers—it's supposed to bring up the print dialog. if you put it in the draw loop with no arguments, the reason it keeps appearing is because the draw loop is running 60 times a second, and therefore launches the print dialog as soon as you closed it. i can see how this feels like a bug, but it actually works as designed.

**Closed by catarak** 2018-10-25 16:32 UTC
