### ISSUE TITLE
Inconsistent behaviour with external p5 libraries..

### ISSUE THREAD

**Issue by aspenforster** [processing/p5.js-web-editor#1021] opened 2019-04-07 15:04 UTC
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome, Firefox + Edge
- Operating System: Windows
- Steps to reproduce this bug:

https://editor.p5js.org/aspenforster/sketches/CnJHxqp3f

This sketch runs in the Edge browser.. but only if I'm logged out...?
If I'm logged in, I get the "Script error. (: line 0)" error. 

Are external libraries supported by the web editor..?

**Comment by shakeabi** [comment] 2019-04-08 18:32
@aspenforster I'm not able to reproduce the error. It works for me when I try to create the same sketch when I'm logged in.

**Comment by catarak** [comment] 2019-04-09 19:41
@aspenforster thanks for reporting! can you try turning off the accessibility features by going to preferences (the cog icon) -> accessibility -> uncheck all of the boxes? there was a bug a few days ago that i fixed in which these features were being turned on by default.

**Comment by catarak** [comment] 2019-04-09 20:02
@aspenforster i actually ran a database command to reset this, so it shouldn't be an issue anymore!

**Closed by catarak** 2019-04-09 20:02 UTC
