### ISSUE TITLE
Save sync issue

### ISSUE THREAD

**Issue by gravitron-** [processing/p5.js-web-editor#353] opened 2017-05-11 02:27 UTC
Code does not save properly and the editor and server version go out of sync. The failed save is not flagged. The sketch runs the server code rather than the code visible in the editor, resulting in some confusion. Requires constant page refresh to display the saved server code.

For example: A variable is commented out. Code is saved. Further edits are made. Sketch is run but produces unpredictable result. Examining the visible code fails to reveal the issue. Confusion. Page is refreshed. Code now shows that the commented variable has not been commented out, thus the issue.

Will attempt to get more evidence via browser console when the issue next occurs.

**Comment by catarak** [comment] 2017-05-13 23:42
can you add a link to the sketch that's causing this? i'm not able to recreate this issue. and yes, if you see it again, definitely look at the browser console and attach a screenshot if there's any errors.

**Comment by catarak** [comment] 2017-05-24 16:00
i'm going to close this issue since i'm not able to reproduce it. feel free to reopen if this happens again.

**Closed by catarak** 2017-05-24 16:00 UTC
Labels: can't reproduce
