### ISSUE TITLE
Multiple file options

### ISSUE THREAD

**Issue by nimishagarwal76** [processing/p5.js-web-editor#874] opened 2019-03-08 17:41 UTC
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 70.0.3538.77 (Official Build) (64-bit)
- Operating System: Ubuntu 18.04.1 LTS
- Steps to reproduce this bug:
    - Right click on mutiple files

On losing focus file menu needs to be closed. Otherwise it looks ugly when no option is selected from file menu and another file is right clicked.

![screenshot from 2019-03-08 22-44-30](https://user-images.githubusercontent.com/37630020/54044207-6000c680-41f4-11e9-8e01-f36ae64cf025.png)

**Comment by ankur54** [comment] 2019-03-12 05:35
So, is this issue still open, or is it closed? If possible I would like to work on it.

**Comment by nimishagarwal76** [comment] 2019-03-12 05:42
yeah i looking into it

**Comment by catarak** [comment] 2019-03-12 19:51
this is a duplicate of #679

**Closed** 2019-03-14 20:12 UTC
