### ISSUE TITLE
Add A .prettierrc file 

### ISSUE THREAD

**Issue by ashu8912** [processing/p5.js-web-editor#1242] opened 2020-01-17 13:12 UTC
- New feature request

#### Feature enhancement details:
Adding A Global .prettierrc file brings every contributor to follow the same formatting rule.

**Comment by simranaggarwal1999** [comment] 2020-01-18 06:32
Hey! @ashu8912  Can I work upon this issue?

**Comment by catarak** [comment] 2020-01-28 20:40
duplicate of #861

**Closed by catarak** 2020-01-28 20:40 UTC
Labels: duplicate
