### ISSUE TITLE
In shortcuts referring the shortcut key of  "ctrl" as ctrl itself instead of ^ as it would make it easier to understand the shortcut keys 

### ISSUE THREAD

**Issue by aditya123473892** [processing/p5.js-web-editor#2798] opened 2023-12-28 17:25 UTC
### Increasing Access

it might make the shortcut keys more understandable as other shortcut keys like "enter" are   referred normally 
![ctrl error](https://github.com/processing/p5.js-web-editor/assets/117269123/817f737d-db6b-4b7f-afd4-67367f5c8898)

### Feature enhancement details

just referring the  ctrl key as  ctrl instead of  "^"

**Comment by aditya123473892** [comment] 2023-12-28 17:26
if  u guys think that this  might be an good enhancement can i be assigned to fix it

**Comment by lindapaiste** [comment] 2023-12-28 19:09
I'm going to close this as a duplicate of #2355 

We have a PR pending to change it.  The only holdup there was a question about menu styling/width. #2465

**Closed as not planned** 2023-12-28 19:09 UTC
Labels: Enhancement
