### ISSUE TITLE
Touch functions not registering in full screen mode

### ISSUE THREAD

**Issue by Loquatious-Celea** [processing/p5.js-web-editor#2112] opened 2023-02-03 17:16 UTC
#### Details about the bug: When trying to share example code in full screen mode, touch functions do not register to the code at all.

- p5.js version: <v.1.5.0>
- Web browser and version: 
- Operating System: <All current mobile systems including iPadOS16.3, iOS16.3-->
- Steps to reproduce this: Take any working touch screen code, file --> share --> Fullscreen link --> attempt to use touch screen functions
- 

let value = 0;
function draw() {
  fill(value);
  rect(25, 25, 50, 50);
  describe('50-by-50 black rect turns white with touch event.');
}
function touchStarted() {
  if (value === 0) {
    value = 255;
  } else {
    value = 0;
  }
}

//the code used above is from the reference library, touch presses move the canvas, but do not register to code in full screen mode-->

**Comment by quinton-ashley** [comment] 2023-02-11 13:01
I had a user in my discord server report a similar problem but I haven't tested it out myself yet.

**Comment by raclim** [comment] 2024-01-19 20:51
I haven't been able to reproduce this issue yet. Since there hasn't been any recent reports/activity on this I'm going to close this issue for now, but please feel free to reopen this or create a new issue if it persists, thanks!

**Closed as not planned by raclim** 2024-01-19 20:51 UTC
Labels: Bug
