### ISSUE TITLE
P5.JS online editor is not working on Safari version 14.1

### ISSUE THREAD

**Issue by yesanpark** [processing/p5.js-web-editor#1877] opened 2021-05-26 05:15 UTC
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by yesanpark** [comment] 2021-05-26 05:17
I cannot use the P5.Js Online Editor on Safari version14.1. Before the new version it had worked well. What's wrong with the version 14.1 Safari on running the P5.JS?

**Comment by peilingjiang** [comment] 2021-05-27 13:43
Currently, you can change
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.1/addons/p5.sound.min.js"></script>
```
to
```
<script src="http://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.1/addons/p5.sound.min.js"></script>
```
in `index.html`, or just remove this line (if you are not using p5 sound) to avoid this error.

**Comment by yesanpark** [comment] 2021-05-28 07:42
@peilingjiang 
Thanks for the comments, but
It's still not working with the downloaded Editor of p5.js or its online Editor on Safari. 
I can run it online with Chrome.

I think the p5.js Editor doesn't work on Safari after Apple updated its browser.

**Comment by outofambit** [comment] 2021-05-29 20:30
Tried this and was able to reproduce in Safari 14.1.1 on macOS 11.4. Error appears to be a CORS issue:

`AbortError: Failed to fetch module, error: Cross origin requests are only supported for HTTP.`

I have on idea why this would affect the p5 sound URL but not the p5 core library URL, as they are both HTTPS and from the same domain... hopefully @catarak has an idea?

**Comment by catarak** [comment] 2021-06-04 20:18
Thanks for reporting! I'm unfortunately not able to run Safari 14.1.1 because I'm running Big Sur (and therefore running 14.0.3). Apparently the 14.1.1 update is for Catalina and Mojave. So it's hard for me to get more info!

**Comment by catarak** [comment] 2021-06-14 19:49
Just pushed a release ([v1.4.1](https://github.com/processing/p5.js-web-editor/releases/tag/v1.4.1)) that fixes this, closing!

**Closed as completed by catarak** 2021-06-14 19:49 UTC
