### ISSUE TITLE
😱 Crashes and data loss

### ISSUE THREAD

**Issue by bensk** [processing/p5.js-web-editor#110] opened 2016-09-27 15:14 UTC
My students are seeing a pretty frequent error where their editor goes to a white screen and all work is lost since the last save. I know this isn't a very helpful report, but it's a **HUGE** issue that has pushed us back to the desktop editor. 

Anything else I can send that would be helpful?

**Comment by lmccart** [comment] 2016-09-27 15:32
The web editor has not actually been released yet, it is still very much in development and will not officially be live until later this fall. Currently we have it at a hidden alpha url with no links from the main site. I would suggest using the desktop editor until it is officially released. 

If you do want to keep testing it experimentally before it's released, big reports posted in the issues are very helpful, describing what went wrong and any steps to reproduce. Thank you for your patience and help.

@catarak @shiffman maybe we should make this more clear? a popup on page load? or even put it behind a password wall?

**Comment by bensk** [comment] 2016-09-27 15:39
Sorry, should've prefaced with a. totally understand it's alpha and we shouldn't complain and b. @shiffman and @catarak were kind enough to share it with a group of NYC teachers who are teaching p5 this year in 8th and 12 grade.

**Comment by shiffman** [comment] 2016-09-28 21:04
@lmccart I think a pop-up or note at the top could be ok, but a password wall would probably cause too much grief for the students.   @bensk we've had the same issue at ITP, it mostly happens if a student writes an infinite loop by accident (see: #77).  One temporary fix is to have them press "stop" (to disable autorun) until they finish typing and then make sure they save often.  It's hard to remember, but it helps.  I've also just been telling students it's a fact of life with an alpha web editor that they might lose their code from time to time and it's something we all have to live with.  I have them sometimes copy/paste sketches to github gists at moments when they have something they can't live without.  I can see how this might be trickier in a middle/high school environment.

**Comment by catarak** [comment] 2016-09-28 22:00
Today, @yining1023 and I just merged in some code to watch for infinite loops which will hopefully help with this issue, to be deployed to production later tonight.

I'm also currently working on #3 which I will hopefully finish and deploy tonight.

**Comment by lmccart** [comment] 2016-09-29 18:20
Ah @bensk got it, sorry, I didn't put the names together and worried that this link was leaking out there. Thanks for reporting the issues!

**Comment by catarak** [comment] 2016-09-29 18:37
Also @bensk if you have any more details as to what may have caused the sketches to crash
- Which accounts?
- Which specific sketches?

**Comment by kjhollen** [comment] 2016-10-05 19:19
We saw this in class today, too. 

Student said he hadn't saved the sketch yet, but user account is whartonwi

**Comment by catarak** [comment] 2016-10-05 21:22
@kjhollen did you happen to be using the console?

**Comment by kjhollen** [comment] 2016-10-05 21:40
@catarak I'm not sure. I can ask the student when we have class again next week. we haven't shown the students the console yet in class, but that doesn't mean that they didn't find it or weren't using it... more soon. 

also worth mentioning that I tried to open up the chrome dev tools & was met with an error message (couldn't connect to the page, or something like that). nothing would load in the inspector.

**Comment by kjhollen** [comment] 2016-10-06 17:55
follow up: ran into the student after class yesterday. He was not using the console and had just created a new, unsaved sketch.

**Comment by catarak** [comment] 2016-10-06 20:02
@kjhollen thanks for the detailed info! hopefully i'll be able to figure out what's happening soon

**Comment by kjhollen** [comment] 2016-10-13 19:32
I want to add some more detail (just experienced this on my own computer). Had a sketch open from class yesterday and browser tab was open for about 24 hours. Laptop has been closed / put to sleep multiple times since then. When returning to the tab, code is visible for a moment then entire screen blanks out.

**Comment by catarak** [comment] 2016-10-14 16:11
From that description it seems like there's a memory leak, good to know, thanks!

**Comment by catarak** [comment] 2021-02-09 18:35
I'm going through and closing some older issues. I'm not sure this is fixed, but I'm going to close it since I haven't heard this issue coming up in a while. Feel free to create a new issue to report crashes!

**Closed by catarak** 2021-02-09 18:35 UTC
Labels: type:bug
