### ISSUE TITLE
The word "circle()" is not colored in the High Contrast mode

### ISSUE THREAD

**Issue by barik10101** [processing/p5.js-web-editor#983] opened 2019-03-24 16:43 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [x] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by AnkurIngale** [comment] 2019-03-24 22:09
I'll do it.

**Comment by AnkurIngale** [comment] 2019-03-24 22:11
Ill fix this.

**Comment by plxity** [comment] 2019-03-25 04:04
@AnkurIngale Try to make it similar as shown in the pic.
![Capture](https://user-images.githubusercontent.com/28510494/54894534-121cdb80-4ee1-11e9-8b29-34d7f4163898.PNG)

**Comment by AnkurIngale** [comment] 2019-03-25 18:12
circle is not a keyword. Infact, all these words https://editor.p5js.org/Janglee123/sketches/z5DUgwwjy are not keywords. Either, we should make them keywords or make a separate group for them. Views @catarak @plxity ?

**Comment by catarak** [comment] 2019-03-26 17:02
thanks for reporting! i'm going to mark this as a duplicate of #978.

**Closed** 2019-03-26 17:03 UTC
Labels: duplicate
