### ISSUE TITLE
Network Request for p5.js for each compilation

### ISSUE THREAD

**Issue by ashu8912** [processing/p5.js-web-editor#1245] opened 2020-01-21 19:25 UTC
- Found a bug
if we compile our code in the web editor for each compilation the p5 libraries are re-requested which is an unideal behaviour generally once these lib files are downloaded they shouldn't be fetched again for each compilation.

- Steps to reproduce this bug:
1. Take any sketch and then open the network tab.
2. Now press the play button to compile the code.
3. For each compile, the p5.js and other libs are refetched.

After One Press.
<img width="487" alt="Screenshot 2020-01-22 at 12 47 32 AM" src="https://user-images.githubusercontent.com/30126128/72835954-ad254400-3cb1-11ea-818e-eaee097dd099.png">
After Second Press
<img width="906" alt="Screenshot 2020-01-22 at 12 47 41 AM" src="https://user-images.githubusercontent.com/30126128/72835963-b0203480-3cb1-11ea-94db-54a44856c5a9.png">

**Comment by ashu8912** [comment] 2020-01-21 19:25
@catarak @andrewn

**Comment by catarak** [comment] 2020-01-28 21:09
duplicate of #463

**Closed by catarak** 2020-01-28 21:09 UTC
