### ISSUE TITLE
2d array for loop crash

### ISSUE THREAD

**Issue by joemckay5** [processing/p5.js-web-editor#286] opened 2017-01-29 22:13 UTC
Okay, this one's odd, and not an emergency. 
I'm making a tic-tac-toe game that plays itself. This is a stripped down version to try and isolate the bug. 
It occurs when accessing a 2d array to display the stored data of the game. If I don't use an else statement the program hangs after 25 to 40 "games". This may be human error, not a bug, but I'm not seeing the same problem in Processing. 
Uncomment lines 47 48 and 49, and oddly,  the code works fine. 
http://alpha.editor.p5js.org/Joemckay/sketches/B1T7o2jwe

**Comment by catarak** [comment] 2017-01-30 17:24
My hunch is that this has to do with the infinite loop detection code... I'll test this sketch by removing that code and get back to you.

**Comment by joemckay5** [comment] 2017-01-31 18:07
Be careful, if time travel movies have taught me anything it's that you shouldn't go messing with something as dangerous sounding as the "infinite loop protection code". That sh*t's there for a reason! 
:)

**Comment by catarak** [comment] 2017-01-31 18:15
I'm sad to tell you this, but I changed line 44 to an `if` statement instead of an `else if`, and it's working flawlessly for me. Another thing, that maybe has nothing to do with this, but I noticed that the spaces array only contains values of 0 or 1 so it's never drawing X's. I _think_ that's a bug.

...so maybe this is a memory issue? I'm not sure right now.

**Comment by joemckay5** [comment] 2017-01-31 18:29
Hmm, I saved the code with your changes and it crashes for me still. Are you playing it for enough cycles? it crashes after about 25 - 30 games. I'll give it a try on another computer. 
This is code I wrote to try and isolate the bug, it's designed to never makes X's to eliminate possible variables.  
Here's the larger project; 
http://alpha.editor.p5js.org/Joemckay/sketches/H1kfiK9we

**Comment by joemckay5** [comment] 2017-01-31 18:33
Here's something. If you comment out line 25, where we propagate the array in the draw, the code works fine.

**Comment by catarak** [comment] 2017-01-31 18:36
This sounds like an exciting memory issue! My computer is pretty beefy and has 16GB of RAM, so I'll bet that the computer you're using has less memory.

**Comment by joemckay5** [comment] 2017-01-31 18:54
"Exciting memory issue" Lol. 
I just tried it on my PC with 32GB of ram and it crashed at the same point. The other computer is a mac laptop with 8. 
(we're looking at the same sketch right? http://alpha.editor.p5js.org/Joemckay/sketches/B1T7o2jwe)

**Comment by catarak** [comment] 2017-01-31 19:56
It is just... not crashing for me. So strange. I tried Chrome, Firefox, Safari. We'll figure it out!

**Comment by lmccart** [comment] 2017-01-31 19:59
hey @joemckay5 have you confirmed this runs fine without the editor? wondering if I should look into memory leaks with the library?

**Comment by joemckay5** [comment] 2017-01-31 20:01
It works fine in processing - good thinking to try it outside the editor. I'll do that now. 
lmccart, are you seeing the bug?

**Comment by lmccart** [comment] 2017-01-31 20:03
so far no..

**Comment by joemckay5** [comment] 2017-01-31 20:05
Okay, outside the editor it runs fine, so for me it's in the editor. I'm on chrome in both my mac and PC. I'll try other browsers. 
It's possible I've slipped into an alternate reality. Clinton is president right?

**Comment by joemckay5** [comment] 2017-01-31 20:10
Okay, definitely something on my end. Works in Safari and Firefox. Works in Chrome in incognito mode so it must be conflicting with an extension I have.

**Comment by joemckay5** [comment] 2017-01-31 20:25
Turned off all extensions, cleared cookies and history, reset all my chrome settings and it still crashes. 
It does NOT crash, however,  if I logout of google and open a window as a guest. 
Are y'all logged into google through chrome when you run it?

**Comment by catarak** [comment] 2017-01-31 20:30
i am! i just tried running it as a guest and it still didn't crash for me.

**Comment by joemckay5** [comment] 2017-01-31 20:39
It's always crashing after 25 games now. Does this error message mean anything to you? 

<img width="577" alt="screen shot 2017-01-31 at 3 37 47 pm" src="https://cloud.githubusercontent.com/assets/6563969/22483453/58c435f8-e7cb-11e6-9fcc-e45ce0928062.png">

**Comment by catarak** [comment] 2017-01-31 20:58
hmmm, that is an error I've apparently googled before, but it's hard for me to pinpoint without being able to reproduce.

**Comment by catarak** [comment] 2017-05-24 17:40
i'm going to close this since i wasn't ever able to reproduce. feel free to reopen if this comes up again!

**Closed by catarak** 2017-05-24 17:40 UTC
Labels: priority:low, type:bug
