### ISSUE TITLE
What about autofill characters } and ) ?

### ISSUE THREAD

**Issue by EthanHermsey** [processing/p5.js-web-editor#1195] opened 2019-10-14 21:05 UTC
Hey!

I have a request. 
Can there be a function that adds a } character after you type in { and puts the cursor in between?The same for ( and [ characters would be nice. With a checkbox in the options tab.
I would put in a pull request but i can't make any sense of this code repository ;p
Thanks you,

Ethan

**Comment by catarak** [comment] 2019-10-17 17:34
thanks for the suggestion! this project has had a lot of discussion about whether or not to add this feature, see #55 and #941. i'm open to hearing more pros and cons! a guiding principle of this project is keeping the editor simple and not adding a ton of features, so i'd like to add it only if it seems like it would add a lot to the experience.

**Comment by EthanHermsey** [comment] 2019-11-26 17:24
Hey, sorry for the delay in my answer.

I was thinking that more experienced programmers would be more attracted to keep using the editor. 
I use it often to just prototype an idea or test something. It does really work well, with the filesystem, autosave, direct preview of your code, and the code beautifier (which a pretty big feature where i could compare the autocomplete to). But noone really likes typing long code :p I tend to go back to vscode on my machine just for the auto-completion.

People who haven't been coding for long could get confused about characters popping up. On the other hand the feature wouldn't even have to be activated initially, people could add it through the settings menu. 
It's also hard to draw the line, what characters should you complete.. {}, (), [], '', "", maybe ``? Do you also do function/variable names?

This is my contribution to this discussion, thank you :) Ethan

**Comment by catarak** [comment] 2019-12-05 20:27
I hear you! Part of me feels like it's the kind of thing that newer programmers should "practice" keeping track of opening and closing braces/brackets, but since basically every text editor out there autocompletes them by default, maybe it doesn't make any sense. I'm also compelled by how many times this issue has been submitted.

**Comment by catarak** [comment] 2019-12-12 19:24
I'm going to close this as a duplicate of #941, but this discussion is still very much alive!

**Closed by catarak** 2019-12-12 19:24 UTC

**Comment by EthanHermsey** [comment] 2020-12-11 17:24
You've added it! That's amazing! I'm so happy with it, thanks! :D

**Comment by catarak** [comment] 2020-12-11 19:29
Yay! Glad it's useful to you ✨
