### ISSUE TITLE
Optimizing Add to Collection List Icons for Enhanced Intuitiveness and User-Friendly Interaction.

### ISSUE THREAD

**Issue by Ri-Sharma** [processing/p5.js-web-editor#3010] opened 2024-02-10 17:54 UTC
### Increasing Access

Currently, the Add to Collection List icons are not as intuitive as they could be, leading to user confusion and challenges in identifying whether an item is already part of the collection. Additionally, the current design poses difficulties for mobile users who lack hover functionality.

### Feature enhancement details

 To enhance the user experience and provide a more intuitive design, I recommend modifying the interface to exclusively display the "add" or "remove" icon upon item selection, without relying on hover functionality. This adjustment not only addresses the challenge of identifying whether an item is already part of the collection but also caters to mobile users who lack the hover capability.

By removing the check mark when an item is not hovered, users will experience a cleaner and more streamlined visual representation. This refinement not only improves accessibility for mobile users but also contributes to a more user-friendly design, fostering a seamless and efficient interaction with the collection interface.

**Comment by lindapaiste** [comment] 2024-02-12 01:25
This is something that I brought up a while ago and that I definitely think we should fix.  There was a PR but it got off-track because I made a suggestion and the contributor interpreted it differently that what I meant.  So I will definitely check out your PR at some point.

I'm going to close this issue as a duplicate of #2255 to keep all discussion in one place.

**Closed as not planned by lindapaiste** 2024-02-12 01:25 UTC
Labels: Enhancement
