### ISSUE TITLE
Editor does not save properly

### ISSUE THREAD

**Issue by anti-ghost** [processing/p5.js-web-editor#1648] opened 2020-10-20 21:24 UTC
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

When I save a project, even though it's saved, the browser thinks the project is not saved, and the browser gives me a message warning me about unsaved content.

- Web browser and version:  Google Chrome 86.0.4240.75 (Official Build) (64-bit) (cohort: Stable)
- Operating System:  Windows 10 Home 64-bit (10.0, Build 18362)
- Steps to reproduce this bug: Save a project, then reload the editor.

![p5](https://user-images.githubusercontent.com/34798985/96645504-8303bf80-12df-11eb-8223-2cec55da1aec.png)

**Comment by catarak** [comment] 2020-10-21 18:38
Thanks for reporting! I have also noticed this behavior. This is a duplicate of #1633 so I'm gonna close this one!

**Closed as completed by catarak** 2020-10-21 18:38 UTC
