### ISSUE TITLE
Using "My assets"

### ISSUE THREAD

**Issue by dlefur** [processing/p5.js-web-editor#794] opened 2018-12-24 00:35 UTC
#### Nature of issue?

- New feature request

#### New feature details:

Hello, I don't find explanation about how to use "My assets". I did see all my imported files, but I don't know how to use them in other sketches, without duplicating.
Thanks.

**Comment by catarak** [comment] 2019-01-08 22:50
Hi @dlefur! As of right now, you can't move your assets across multiple sketches. This is a feature of the web editor that's not totally built out, to be able to manage your assets outside of a specific sketch. There are open issues about it, see #498, #393, #673, #168, #225.

**Comment by catarak** [comment] 2019-01-08 22:50
I'm going to close this as it's a duplicate of #225, but feel free to reopen if you think that's not right.

**Closed by catarak** 2019-01-08 22:50 UTC

**Comment by dhhepting** [comment] 2019-03-31 06:15
I have a question about removing assets from the editor: I've added some files there that I would like to delete. I noted that the illustration in #393 shows download and delete functionality.  I see that at present, I am able to download assets but I have not found a way to delete assets. Is this feature currently available? I'm using Chrome Version 73.0.3683.86 (Official Build) (64-bit) on macOS Version 10.13.6 (17G5019).

**Comment by catarak** [comment] 2019-04-03 16:22
@dhhepting you can delete assets by going directly into the sketch, and deleting the file there. i know it's not perfect, and it is annoying if you want to delete lots of files.

**Comment by dhhepting** [comment] 2019-04-03 21:16
@catarak Thank you for the reply. I have been using the editor for a few months now but I had not discovered the project-folder view.  Looking at "my assets", I thought that the issue was small but now that I see the project-folder view, I realize that my problem is big (lots of files to delete).  A few things come to mind as desirable features: 

- the ability to delete an entire sketch, or to revert the project-folder to its original contents (remove all files and folders that were added to the sketch's project-folder by the user)
- a more accessible way to access the project-folder view: perhaps a choice to have it open by default
- synchronization between "my assets" and the project-folder so that the 2 views show the same files
- a check for allowable file types when adding files, so that only files capable of being used by p5.js are allowed to be uploaded
- a dialogue box to confirm a request to upload a lot of files or to confirm if a file to be uploaded has the same name as an existing file that a separate version should be created (e.g. file, file-1, file-2)

I am willing to help out with development and documentation.  And to distribute my suggestions, above, to the appropriate places.  :-)

**Comment by catarak** [comment] 2019-04-04 18:20
i'm going to respond to your feature requests:

> * the ability to delete an entire sketch, or to revert the project-folder to its original contents (remove all files and folders that were added to the sketch's project-folder by the user)

you can delete a sketch by going to File -> Open, hovering over the sketch you want to delete, and then clicking on the trash can that appears. i admit it is not the best UX. it will soon change to a down arrow in which you can select multiple sketch options, one of which is delete sketch.

> * a more accessible way to access the project-folder view: perhaps a choice to have it open by default

i don't understand why i have waited so long to fix this UX bug. the sidebar arrow just needs to be... bigger, brighter, more of a CTA. i agree! it's hard to find.


> * synchronization between "my assets" and the project-folder so that the 2 views show the same files

"my assets" is supposed to be all of your assets in all of your projects, whereas the project folder just contains the files that are in your project.


> * a check for allowable file types when adding files, so that only files capable of being used by p5.js are allowed to be uploaded

this does exist! there is a small list of whitelisted file types. i think the feedback if you've uploaded a file that p5 doesn't like isn't.


> * a dialogue box to confirm a request to upload a lot of files or to confirm if a file to be uploaded has the same name as an existing file that a separate version should be created (e.g. file, file-1, file-2)

this is captured as #734. 


> I am willing to help out with development and documentation. And to distribute my suggestions, above, to the appropriate places. :-)

i welcome any and all of your support! there are lots of open issues to choose from, and i recommend working on high priority stuff, or things you want to see in the web editor.
