### ISSUE TITLE
The translation feature for the Terms of Service on the Sign-Up page is not working correctly.

### ISSUE THREAD

**Issue by GARY121github** [processing/p5.js-web-editor#2863] opened 2024-01-07 10:41 UTC
### What is your operating system?

Windows

### Actual Behavior

The translation feature should accurately translate the Terms of Service into the selected language.
![Screenshot (183)](https://github.com/processing/p5.js-web-editor/assets/108233340/0c11a273-274c-48ea-ba68-c55917c1ddb4)

### Expected Behavior

The translation feature is not working correctly, and the content remains in the default language.

### Steps to reproduce

1. Navigate to the Sign-Up page on the p5.js Editor.
2. Change the language into any other language.
3. Notice that the translation feature is not providing accurate translations or is not functioning as expected.

**Comment by shivapranav07** [comment] 2024-01-07 11:48
is this issue is approved

**Comment by 0Kaju12** [comment] 2024-01-07 12:17
@shivapranav07 Someone has already addressed this issue and sent a PR but it has not been merged yet

**Comment by arpitghura** [comment] 2024-01-07 12:30
I would like to work on this issue, if not resolved.

**Comment by lindapaiste** [comment] 2024-01-07 18:39
> @shivapranav07 Someone has already addressed this issue and sent a PR but it has not been merged yet

Actually it's merged but it hasn't been released into production yet.  We only push changes to production every month or so.

Closing as a duplicate of #2846.  We have English and Hindi added by @harmanbatheja15 in #2847.  Feel free to open PRs with additional language translations.

**Closed as completed by lindapaiste** 2024-01-07 18:39 UTC
Labels: Bug
