### ISSUE TITLE
Upload file option is missing

### ISSUE THREAD

**Issue by meghna512** [processing/p5.js-web-editor#1914] opened 2021-08-16 09:28 UTC
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Version 92.0.4515.131 (Official Build) (64-bit)
- Operating System: Ubuntu 20.04.2 LTS
- Steps to reproduce this bug: I am no longer able to upload an image into a folder. So when I create a new project and add a new folder. If I click on this folder, I am only able to Add File (Create) and not actually Upload File. So I am unable to upload an image into a folder.

**Comment by kjhollen** [comment] 2021-10-27 21:37
Hi @meghna512, I believe this occurs when people are not logged into the editor (currently expected behavior). Can you please clarify whether or not you were logged in when this occurred?

**Comment by kjhollen** [comment] 2021-11-12 18:53
Closing this issue because there hasn't been any activity. Feel free to re-open if you can provide more details. Thanks!

**Closed as completed by kjhollen** 2021-11-12 18:53 UTC
