### ISSUE TITLE
Student managed to make an account where user id was set to an e-mail address

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js-web-editor#655] opened 2018-06-21 00:00 UTC
One of my students was having trouble with the editor experiencing some really odd behavior. Her sketches would stutter about once every 60 frames or so, and some sketches would play really awful screeching sounds even though no audio code was being used. I tried running her sketches when she was logged out, or copy pasted into a window where I was logged in and they worked without any hiccups. 

I noticed that her username was an e-mail address, so I had her change the user name to see if that would fix things, but the errors persisted. Eventually I had her make a new account which is working without issue so far. I'm not sure how she even got the e-mail address set as her user name because the page checks that it doesn't have special characters and is less than 20 chars long when you sign up.

I just checked the sketches that were throwing weird behavior again and they look fine, so I'm not really sure how to go about recreating this error, but I wonder if it's at all related to the folks who were  having trouble logging in in https://github.com/processing/p5.js-web-editor/issues/637

I can send the troublesome account info privately if it helps.

#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

**Comment by catarak** [comment] 2018-06-21 23:52
wow this is a crazy bug! maybe it's possible to set a username to an email address if you log in through google or github, and that should be handled differently?

**Comment by aferriss** [comment] 2018-06-22 19:23
Yea, I felt a little crazy even writing it up. The student used the institutions e-mail address though so it followed a pattern of first letter of first name + last name + @ + prefix.institution.edu

so for me that address would be aferriss@inside.artcenter.edu

**Comment by skavanker** [comment] 2018-10-28 11:35
The sound bug happens to me to on this sketch.

https://editor.p5js.org/skavanker/sketches/BkEuvwzn7

I don't know why this would have anything to do with email address, but I did created an account with a google account and then it sets the user as the email.  then you can change username in settings. 

The problem is only there when I'm logged in on, and both in Firefox and Chrome. It also persist when I copy paste it to a new sketch.

This was the simplest sketch I could do to recreate the sound

https://editor.p5js.org/skavanker/sketches/HygQRM7hQ

If there is no movement the sound also stops.

**Comment by catarak** [comment] 2018-10-28 22:28
super weird! can you try opening the JavaScript console and pasting any errors here?

**Comment by catarak** [comment] 2018-10-29 16:48
actually. before that, can you see if you have any of the accessibility features turned on? click on the cog icon -> accessibility -> make sure everything is unchecked.

**Comment by skavanker** [comment] 2018-10-29 17:03
> 
> 
> actually. before that, can you see if you have any of the accessibility features turned on? click on the cog icon -> accessibility -> make sure everything is unchecked.

Yes....sound was enabled in accessibility tab. That fixed my problem. Can't remember I turn it on but I must have. (any shortcuts to turn it on?) Anyway, thanks for the help.

**Comment by catarak** [comment] 2018-10-29 17:09
I don't think so, but it seems like lots of folks are accidentally turning them on.

**Comment by catarak** [comment] 2019-04-18 22:21
closing as a duplicate of #760

**Closed** 2019-04-23 17:01 UTC
Labels: duplicate
