### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by shinytang6** [processing/p5.js-web-editor#562] opened 2018-02-21 13:38 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

when l am on #561, l found this bug :)
l don't know if it maybe relates to #481 or #480, but it seems that the current bug is the username not dealt with when logging in. It should ignore the space after the username.

**Comment by catarak** [comment] 2018-02-21 19:48
yes! we should probably strip whitespace from the username. also for the password? what's the expected behavior here?

**Comment by shinytang6** [comment] 2018-02-22 14:46
l just tested Google and Github and found both of them allow spaces in password..But it seems that some other sites like twitter don't support.
Here is a discussion: https://stackoverflow.com/questions/5475071/should-whitespace-characters-be-allowed-in-a-password
l think it's ok to allow whitespace in password :) at least they are visible.
And if we want to make the password stronger, we should restrict it to like 8 characters or more, with any combination of letters, numbers, and symbols:)

**Comment by catarak** [comment] 2018-02-22 20:58
i agree that it's okay to have whitespace in a password. i'm not sure about password strength enforcement—i know that certain rules can be really arbitrary and i'm not up to date on good rules vs bad ones. open to suggestions and resources!

**Comment by shinytang6** [comment] 2018-02-23 16:04
l think there will be no problem with simple password currently for the reason that all the sketches/assests are public, the enhancement of password strength should be added if features like private sketches are implemented:)

**Comment by catarak** [comment] 2018-02-23 17:02
maybe i will get some opinions from infosec friends and see what i come up with 💃

**Comment by crhallberg** [comment] 2018-03-26 23:09
Copy from referenced issue: The same thing is occurring with one of my students. Username: monterw1. Uses a password manager, so definitely not an mistyping error and he says there's no space in his password.

**Comment by shinytang6** [comment] 2018-03-27 07:29
Hi @crhallberg, can l ask is there any trailing whitespace in the username when he signs up or logs in?

**Comment by Laphatize** [comment] 2018-03-30 21:27
@crhallberg I suggest you tell him to type it up manually. Sometimes auto-fill is a little buggy.

**Comment by catarak** [comment] 2018-10-25 20:32
i'm going to close this as a duplicate of #480, and outline some steps on that issue of possible fixes. removing whitespace!

**Closed** 2018-10-25 20:33 UTC
