### ISSUE TITLE
Login Session Still Persists Despite Logout

### ISSUE THREAD

**Issue by Ankush263** [processing/p5.js-web-editor#2449] opened 2023-09-16 20:58 UTC
### p5.js version

1.7.0

### What is your operating system?

Windows

### Web browser and version

chrome, edge, Brave

### Actual Behavior

When we try to log out, the session Id is not deleted

![Screenshot (92)](https://github.com/processing/p5.js-web-editor/assets/86042508/364c1c50-f32d-4b7f-9985-f0c90bc4ab57)
![Screenshot (95)](https://github.com/processing/p5.js-web-editor/assets/86042508/968e1544-2548-4054-b1fc-d146dafa6a8e)
![Screenshot (93)](https://github.com/processing/p5.js-web-editor/assets/86042508/fbcd0903-9a2c-4fde-8c4d-60c2f484d0b9)
![Screenshot (94)](https://github.com/processing/p5.js-web-editor/assets/86042508/5f245776-a913-4296-9e65-f5a56c91c324)

As a result, after clicking logout, when I refresh the page, I again enter the login state on the website.

### Expected Behavior

The sessionId got deleted and after refresh, the user can not go back to the login state.

### Steps:
1. click logout.
2. hit refresh
3. you get back to login state

**Comment by Ankush263** [comment] 2023-09-16 21:04
I think this is happening because this line of code inside `/server/controllers/session.controller.js`

![image](https://github.com/processing/p5.js-web-editor/assets/86042508/34666ec1-072d-4477-b299-0b8ad225ee6f)

Here, `req.logout` does not delete the session Id, so it still remains the same
I'm gonna raise a PR to resolve this issue

**Comment by niikkhilsharma** [comment] 2023-09-16 23:43
I welcome this opportunity to contribute this repo and fix the issue. Can you please assign this task to me.

**Comment by pankajdharmik4** [comment] 2023-09-17 03:32
Are you working on this issue?

**Comment by lindapaiste** [comment] 2023-09-17 22:18
This is probably a duplicate of #2292

Right now on production if I hit "log out" I get a 500 Internal Server error from the API.  That error was fixed by #2299 but I don't think we've pushed to production since.

Regarding the session id, I honestly don't understand cookies that well so I'm not sure if a change is needed there or if the previous fix is enough.  We are using `passport` to manage the login and I suspect that when the API works properly calling `req.logout` will destroy the session id.

**Comment by Ankush263** [comment] 2023-09-18 02:21
But in this case req.logout does not delete the session id, that's why when you hit refresh, you again got into login state

**Comment by lindapaiste** [comment] 2023-09-18 03:06
> But in this case req.logout does not delete the session id, that's why when you hit refresh, you again got into login state

Are you able to see this happening (session id not deleted) on `localhost`?  If it's only happening on production then I really think it's due to the `req.logout` function not firing at all, due to the bug.  You have found that bug but I think that what you are seeing with the session id is a symptom rather than a cause.

Again I am not on expert in this area but here is what the [passport docs](https://www.passportjs.org/concepts/authentication/logout/) say:
> Passport exposes a `logout()` function on `req` (also aliased as `logOut()`) that can be called from any route handler which needs to terminate a login session. Invoking `logout()` will remove the `req.user` property **and clear the login session** (if any).

**Comment by Ankush263** [comment] 2023-09-18 04:41
Ok, I understand👍

**Comment by rajatmohan22** [comment] 2023-09-23 20:07
@lindapaiste I might have found a way to resolve this issue. Do check: #2473

**Comment by dhowe** [comment] 2023-10-03 09:39
Also have this serious bug on firefox/chrome for mac.

Occurs not only on refresh, but also opening a new tab/window:

1. logout of account
2. close tab
3. open new tab 
4. still logged in

**Comment by lindapaiste** [comment] 2023-11-02 19:56
I am still trying to understand if we need to explicitly destroy the session or not.  Looking at the passport source code, **I really think that we do not need to do anything extra**.

1. API hits `/logout` endpoint
2. => calls our function `SessionController.destroySession`
3. => calls `req.logout`, which is a `passport` function
4. => calls internal `passport` function `this._sessionManager.logOut`
5. => deletes the `user` from the session so that it cannot be used

Source codes:

`req.logout`
https://github.com/jaredhanson/passport/blob/cfdbd4a762b51e339ebfea931d65bccbbde53282/lib/http/request.js#L48-L71

`sessionManager.logOut`
https://github.com/jaredhanson/passport/blob/cfdbd4a762b51e339ebfea931d65bccbbde53282/lib/sessionmanager.js#L57-L93
Comments say
```
  // clear the user from the session object and save.
  // this will ensure that re-using the old session id
  // does not have a logged in user
```

**Closed as completed** 2023-11-02 19:59 UTC
Labels: Priority:High, Bug

**Comment by rajatmohan22** [comment] 2023-11-02 20:06
1. It's working fine for me. I don't see any 500 status code or errors. Should I record a YouTube video?
2. Destroying sessions is generally a good idea. Changing the status ID isn't any different from logging the user out, so why not clear unnecessary data from the codebase? Storing these sessions isn't an optimized technique in my opinion.

**Comment by rajatmohan22** [comment] 2023-11-02 20:10
I suggest clearing the browser cache just in case it stores user-related snapshots from previous sessions. However, I believe 'res.destroy' should suffice.

**Comment by rajatmohan22** [comment] 2023-11-02 20:21
@lindapaiste You might have gotten the order of operation wrong.
What is happening is this:

1. An API request hits the "/logout" endpoint.
2. "req.session.destroy" clears the user's server-side session, logging them out.
3. If an error occurs during session destruction, it's passed to the error handler.
4. "req.logout" (typically from Passport.js) removes the user from the session (THIS WILL NOT CAUSE AN ERROR AS SESSION IS NOT DESTROYED UNTIL THE FUNCTION IS FULLY BEEN EXECUTED)

A workaround for this would be to just call the res.session.destroy. It would serve the purpose of destroying the session and not causing this particular error. However, To me this is working fine

**Comment by rajatmohan22** [comment] 2023-11-02 20:23
Your explanation works for a code like this:
```
req.session.destroy()
req.logout()
```

But this is,
`req.session.destroy(req.logout())`

**Comment by lindapaiste** [comment] 2023-11-02 22:06
Does it work for you if the order is swapped?  It works for me like this:
```
export function destroySession(req, res, next) {
  req.logout((err) => {
    if (err) {
      next(err);
      return;
    }
    req.session.destroy((err) => {
      if (err) {
        next(err);
        return;
      }
      res.json({ success: true });
    });
  });
}
```

**Comment by lindapaiste** [comment] 2023-11-02 22:15
It looks like we are using a very outdated version of the `connect-mongo` package (we're on 1.x and they're up to 5.x).  There is some info in their docs about removing expired sessions from MongoDB but this is for the current version: https://www.npmjs.com/package/connect-mongo#remove-expired-sessions

**Comment by lindapaiste** [comment] 2023-11-02 22:21
> Your explanation works for a code like this:
> 
> ```
> req.session.destroy()
> req.logout()
> ```
> 
> But this is, `req.session.destroy(req.logout())`

The inner function `req.logout` is the callback, so that means that it gets executed by the `req.session.destroy` function after that function has executed its primary job (destroying the session).

I don't know why it's different in your environment than in mine.  All I know is that I'm getting the error 🤷 .  Try adding these two `console.log` statements and tell me what you see.
```
export function destroySession(req, res, next) {
  console.log('here there is a session', !!req.session, req.session);
  req.session.destroy((err) => {
    if (err) {
      next(err);
      return;
    }
    console.log('here there is no session', !req.session, req.session);
    req.logout((error) => {
      if (error) {
        next(error);
        return;
      }
      res.json({ success: true });
    });
  });
}
```
Here is what I see:
```
here there is a session true Session {
  cookie: {
    path: '/',
    _expires: null,
    originalMaxAge: null,
    httpOnly: true,
    secure: false
  },
  passport: { user: '63fc0d0e7cf578097886cb43' }
}
here there is no session true undefined
Error: Login sessions require session support. Did you forget to use `express-session` middleware?
    at SessionManager.logOut (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\passport\lib\sessionmanager.js:64:33)
    at IncomingMessage.logout (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\passport\lib\http\request.js:67:26)
    at C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\server\controllers\/session.controller.js:41:9
```

**Comment by rajatmohan22** [comment] 2023-11-03 02:00
I am a little confused but swapping does make it seem better logic wise (ie to delete the session once the user has been logged out) . So I can do that If you want. 
Shall I open another PR?
