### ISSUE TITLE
Not working import tag.

### ISSUE THREAD

**Issue by AndrewAung11** [processing/p5.js-web-editor#1777] opened 2021-02-23 09:56 UTC
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: On `Chrome 88.0.4324.182 (Official Build) (64-bit) (cohort: Stable)`
- Operating System: Windows along with 8.1 Pro
- Steps to reproduce this bug:

The import link of p5.js lib is not working anymore. But it is still used in [p5.js web editor](https://editor.p5.js). If I run the p5.js code with the default import tag the editor doesn't show anything but when I delete the default tag an paste a tag from [cdnjs](https://cdnjs.com) it show what I code.

#### The picture when I run the editor with default import tag.
![image](https://user-images.githubusercontent.com/64914752/108827134-9d360d00-75f3-11eb-8177-0230d2bf52bc.png)

**Comment by catarak** [comment] 2021-03-10 18:57
Hi @AndrewAung11! I'm a little confused about the bug you are reporting here. For me, p5.js sketches are working with importing p5.js from `https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.2.0/p5.js`.

**Comment by kjhollen** [comment] 2021-11-12 18:41
Thanks for reporting @AndrewAung11! I'm going to close this because we weren't able to reproduce the issue, but if you're still experiencing the issue and can provide more information, please reopen.

**Closed as completed by kjhollen** 2021-11-12 18:41 UTC
