### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by JPatagonico** [processing/p5.js-web-editor#1324] opened 2020-03-13 22:18 UTC
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### New feature details:
Autocomplete for P5.JS in both the online editor and the Processing editor

**Comment by catarak** [comment] 2020-04-06 18:30
Duplicate of #99.

**Closed by catarak** 2020-04-06 18:30 UTC
