### ISSUE TITLE
loadStrings String Addition/Concatenation in Filepath

### ISSUE THREAD

**Issue by Sunomikey** [processing/p5.js-web-editor#839] opened 2019-02-21 15:30 UTC
#### Nature of issue?
- Found a bug

#### Details about the bug: 
loadStrings() won't load anything past a direct file path. 

What I can do:
loadStrings('test.txt')

OR
x = 'testFolder/test.txt';
loadStrings(x);

What I can't do:
ext = '.txt';
loadStrings('test'+ext');

OR
i = "1";
loadStrings('test'+i+'.txt');

- Web browser and version: Chrome p5 Web Editor 72.0.3626.109 (Official Build) (64-bit)
- Operating System: Windows
- Steps to reproduce this bug:

1. Have file called "test.txt"

2:
```
function preload(){
	let ext = ".txt"
	txt = loadStrings("test"+ext);
}
```
It won't ever leave the preload as it can't find the file. Is there a variable type it's looking for?

**Comment by catarak** [comment] 2019-02-21 21:06
thanks for reporting! i'm not able to reproduce this, for me it is working, see https://editor.p5js.org/cassie/sketches/tk22ndoWs

**Comment by Sunomikey** [comment] 2019-02-21 21:26
Hi @catarak!

That was working for me as well. My problem came with adding strings together to make a filepath.

Modifying your code would be:

```
let txt;
let fileName = 'test';

function preload() {
	txt = loadStrings(fileName+'.txt'); 
}

function setup() {
  createCanvas(400, 400);
  print(txt);
}

function draw() {
  background(220);
}
```

**Comment by meiamsome** [comment] 2019-02-21 21:56
This is the same underlying issue as #813 I believe, that you can't refer to local files properly. #771 #674 also seem at least partially related. All of these cases are referring to local files in the code that aren't being served up correctly.

For example, in @catarak 's sketch above the file at `https://editor.p5js.org/cassie/sketches/tk22ndoWs/test.txt` returns a 404 instead of the correct contents? Do we expect that to return the text content like it returns for images?

**Comment by catarak** [comment] 2019-02-21 21:57
ahh sorry! did not read closely enough 😸

and @meiamsome, yes, you're right. that url should return the text content like it does for images.

**Comment by Sunomikey** [comment] 2019-02-21 22:05
Thanks @meiamsome for linking the other issues. The definition of "When the file names are generated programmatically, rather than just a string inline, it loads the files in a different way." in 674 would be a good way to describe this.

Good to know I'm not crazy and that the example code "should" work.

Thanks for the help everyone!

**Comment by meiamsome** [comment] 2019-02-21 22:13
For anyone looking to work on this, I believe the issue is in this function: https://github.com/processing/p5.js-web-editor/blob/e75c98b299c4912db0e9931b77691725b8024f8c/server/controllers/project.controller.js#L151-L182

Specifically, it does not account for the case where `file.content` is used instead of `file.url`. I'll work on a fix for this in the next few days if someone else hasn't picked it up before then.

@Sunomikey Yes, I can see how this behaviour can be confusing!

**Closed** 2019-02-22 23:05 UTC
Labels: good first issue, help wanted, priority:high, type:bug
