### ISSUE TITLE
Asynchronous data loading JSON is displaying a blank page

### ISSUE THREAD

**Issue by inspiredlabs** [processing/p5.js-web-editor#831] opened 2019-02-15 14:04 UTC
This isn't working:
- Web browser and version:
  - Chrome 74.0.3694.0 (Official Build) canary (64-bit)
  - FF 65.0.1 (64-bit)
- Operating System: MacOSX 10.13.4

Asynchronous data loading JSON example (https://editor.p5js.org/p5/sketches/BJnQVekQOX), borks on either browser above, displaying a blank page.

Both console read: `Failed to load resource: the server responded with a status of 404 ()` & `TypeError: e.data[0].indexOf is not a function`.

Explicitly specifying the URL: `https://p5js.org/assets/examples/assets/bubbles.json`, hangs the Preview window, displaying `Loading...`.

This embedded iframe example works: https://p5js.org/examples/advanced-data-load-saved-json.html

I found the editor after attempting this tutorial (which no longer works, because of CORS): https://www.youtube.com/watch?v=6mT3r8Qn1VY 

It'd be great if you could update the Youtube tutorial to reflect that CORS isn't covered.

**Comment by shiffman** [comment] 2019-02-15 14:12
I can confirm that the error occurs with the editor using the built-in p5 example.

https://editor.p5js.org/p5/sketches/BJnQVekQOX

I was able to get it to work through the following steps:

1. Update the p5 library to 0.7.3.
2. Re-create the `bubbles.json` file manually.

I'm not sure what was causing the error with the example. Here is a working version:

https://editor.p5js.org/codingtrain/sketches/zFsolg5ZJ

**Comment by meiamsome** [comment] 2019-02-16 01:39
The script that generates these was fixed in 65c1c35d10c66e80d06280c82234d0b397ecd7d4 but it looks like the examples on the current site have yet to be updated.

**Comment by meiamsome** [comment] 2019-02-16 03:48
Ok, I've narrowed down the crash behaviour and opened up a specific issue for the more generic form of that ( #833 )

It looks like this example sketch is quite an old version of the one from the p5.js examples so they need to be updated.

**Comment by catarak** [comment] 2019-02-20 20:54
i think there are a few things going on here:

1. as pointed out in #820, #830, the examples that use external assets are broken due to the sunsetting on rawgit. they should be moved to jsDelivr!
2. #833

@meiamsome i'll take a look at your PR for #833, and get a fix for (1) within the next few days.

**Closed** 2019-02-21 22:15 UTC
