### ISSUE TITLE
P5 Web Editor won't preview any sketches

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-web-editor#764] opened 2018-11-14 06:39 UTC
_From @msgarnier on November 13, 2018 21:36_

#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x ] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: Chrome 70.0.3538.102
- Operating System: MacOS Sierra 10.12.5 (16F73)
- Steps to reproduce this:
It seems to be account specific. It was happening to my students, and then it happened to me. Here is a screen shot
![screen shot 2018-11-13 at 3 43 27 pm](https://user-images.githubusercontent.com/25465795/48444456-fe5aaf00-e761-11e8-8db6-567d3eccf4a9.png)
I have tried a different browser, I have tried using another account, I have tried clearing my browsing history completely, and restarting my computer. The sketches can be previewed by another account.

_Copied from original issue: processing/p5.js#3316_

**Comment by shiffman** [comment] 2018-11-14 13:51
Tagging @mithru in case this a p5.accessibility bug?

**Comment by NotACat** [comment] 2018-11-14 17:42
Is this the same issue as #738?

**Comment by msgarnier** [comment] 2018-11-14 18:02
Not sure. In this case it won't run the sketch at all, the error shows up immediately, and it is the same for any sketch that user is trying to preview through the web editor. What's really puzzling about it is it is intermittent, and affecting different users at different times and locations. It was happening to me in a certain building yesterday, I went home and it wasn't happening, and is not happening today in the same building. But I was working with a student in this building today, and it was happening to them. I would think it was an issue with our network if it was happening for all users at the same time in the same place, but that isn't the case.

**Comment by catarak** [comment] 2018-11-14 19:37
@msgarnier make sure that the accessibility features are off, by clicking on the cog wheel icon, clicking on the tab "Accessibility" and unchecking the boxes under "Accessible text-based canvas". if you are still seeing it after doing that, let me know.

**Comment by catarak** [comment] 2019-04-03 18:38
closing due to lack of clarification. i'm going to assume this is a duplicate of #768.

**Closed by catarak** 2019-04-03 18:38 UTC
