### ISSUE TITLE
Incorrect duplicate console information

### ISSUE THREAD

**Issue by shinytang6** [processing/p5.js-web-editor#644] opened 2018-06-03 09:31 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

1. Open a sketch
2. Generate errors or write some console commands e.g `console.log("xxx")`
3. Log in to your account again and run the sketch

And after that each time you login in, the console information will double unless you refresh the page.

**Comment by shinytang6** [comment] 2018-06-03 09:32
l will try to fix it in #639

**Comment by catarak** [comment] 2018-06-04 21:28
interesting bug, thanks for finding and documenting this!

**Comment by kjhollen** [comment] 2021-11-12 17:34
I can't reproduce this one, so I'm going to close it! Probably got fixed with other things somewhere along the way. Thanks for reporting!

**Closed by kjhollen** 2021-11-12 17:34 UTC
