### ISSUE TITLE
the p5.js Web Editior not working by any line code .

### ISSUE THREAD

**Issue by GuntreddyHemanth** [processing/p5.js-web-editor#3222] opened 2024-08-18 06:21 UTC
### p5.js version

v2.14.3

### What is your operating system?

Windows

### Actual Behavior

function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
  rect(width/2, height/2, 100, 50);
} 
![Screenshot 2024-08-18 115014](https://github.com/user-attachments/assets/2a0d475b-d74f-47ce-8c67-d3cdbeada305)

### Expected Behavior

outcome is rectangler box for the above code

### Steps:
1. 2. 3.
### Snippet:
```js

// Paste your code here :)

```

**Comment by raclim** [comment] 2024-08-19 13:21
Thanks for sharing this! I tried poking around a bit, but haven't been able to reproduce this issue. Is this still occurring for you?

<img width="500" alt="Screenshot 2024-08-18 at 1 54 55 PM" src="https://github.com/user-attachments/assets/67940636-c2a9-459d-9bc8-cfb2a62921f4">

**Comment by GuntreddyHemanth** [comment] 2024-08-20 05:08
Yeah! still, it shows me the same error in the p5.js website
https://editor.p5js.org/

device: windows

**Comment by GuntreddyHemanth** [comment] 2024-08-20 05:09
Yeah! still, it shows me the same error in the p5.js website  https://editor.p5js.org/  

device: windows

**Comment by ShivamYadav-12** [comment] 2024-08-22 08:35
@GuntreddyHemanth  I think it is working as I was not able to  reproduce this issue even in windows? Is it still occurring for you?
![Annotation 2024-08-22 134820](https://github.com/user-attachments/assets/2623abcd-c75c-4656-b7ab-20f30738aec3)

**Comment by shadwar123** [comment] 2024-08-26 17:15
@GuntreddyHemanth @ShivamYadav-12 I am not encountering any errors either.

**Comment by GuntreddyHemanth** [comment] 2024-08-26 17:46
Ok, I'll check it out.

**Comment by raclim** [comment] 2024-08-27 17:06
Since this issue hasn't been able to be reproduced by a few folks, I'm going to close this one for now. One potential solution that sometimes works for me is clearing cookies? 

However, please feel free to reopen this is it still persists for you or if anything else comes up!

**Closed as not planned by raclim** 2024-08-27 17:06 UTC
Labels: Bug
