### ISSUE TITLE
i want to report that my game is not starting it is showing loading fr too long it is not error in code was working fine yesterday but not working now

### ISSUE THREAD

**Issue by Drgamer005** [processing/p5.js-web-editor#1875] opened 2021-05-24 07:06 UTC
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by da091005** [comment] 2021-05-29 04:28
Your Issue is very vague/ lacking details/ examples. Nobody is going to be able to “fix” an issue like this.

**Comment by catarak** [comment] 2021-06-11 17:02
Thanks for reporting! I need more details for this issue in order to fix it. Can you link to the sketch that's not working? Do you have any steps to reproduce? Do you have the browser/OS you're using? Thank you!

**Comment by kjhollen** [comment] 2021-11-12 18:51
Since there haven't been any updates on this one in a while, I'm going to close it. If you can provide some additional details about the error, feel free to reopen and we can look into it. Thanks!

**Closed as completed by kjhollen** 2021-11-12 18:51 UTC
