### ISSUE TITLE
save() is not responding on keypress

### ISSUE THREAD

**Issue by sarweshshah** [processing/p5.js-web-editor#1456] opened 2020-06-15 09:14 UTC
#### Nature of issue?
- Found a bug
#### Details about the bug: save() method is not working.
- Web browser and version: **Google Chrome | 83.0.4103.97 (Official Build) (64-bit)**
- Operating System: **MacOSX**
- Steps to reproduce this bug: 
Call save() in the keyPressed()/keyTyped() function. 
The canvas is not downloaded. Console.log() works fine in the keyPressed() function.

Pressing 'p' after running the sketch does not do anything.
https://editor.p5js.org/sarweshshah/sketches/0jjn3_7NQ

**Comment by catarak** [comment] 2020-06-15 16:13
thanks for reporting! i think this is a duplicate of #1443.

**Closed by catarak** 2020-06-15 16:13 UTC
