### ISSUE TITLE
Console.log() printing to browser console instead of p5 console

### ISSUE THREAD

**Issue by CubeOfCheese** [processing/p5.js-web-editor#2518] opened 2023-10-19 18:45 UTC
### p5.js version

most recent I'm assuming.

### What is your operating system?

Windows

### Web browser and version

Firefox Version 118.0.1

### Actual Behavior

Console.log is printing to the browser's console

### Expected Behavior

console.log should print to the p5 editor console

### Steps:
1. open new editor window
2. create a console.log statement
3. hit run
4. open dev tools to see that it is printing to the browser console
### Snippet:
```js
console.log("HI");

```
![p5 console log error screenshot](https://github.com/processing/p5.js-web-editor/assets/16740469/a3dd6784-0b1b-4753-bbf3-579b961fe9d5)

**Comment by marestaing** [comment] 2023-10-19 19:23
I've been running into this issue too both on mobile and web.

**Comment by dcarroll242** [comment] 2023-10-20 14:00
If you're looking for a timeline, this issue just started yesterday (10/19/2023) and seems to be unrelated to the version of p5.js.

This issue is extremely problematic for us teachers. We'll eventually get to all the amazing graphics that p5 has to offer within the canvas, but we start with the basics using the console and vanilla JavaScript within p5's web editor. (students aren't allowed to inspect the page in most school districts)

**Comment by raclim** [comment] 2023-10-20 14:10
We just pushed a [new release](https://github.com/processing/p5.js-web-editor/releases/tag/v2.8.0) to production earlier this week on Wednesday, so this issue probably stems from one of the changes in this release. I'll look into it and will try to have an update for it soon!

**Comment by CubeOfCheese** [comment] 2023-10-20 14:38
FYI I forgot to mention that this is affecting everything meant for the console. So not only console.log statements but all errors and warnings as well.

**Comment by KrishavRajSingh** [comment] 2023-10-20 20:11
can you give me a little hint on how to approach this issue?

**Comment by madtitan02** [comment] 2023-10-20 20:44
I guess the console handler is not Implementing a system to capture and display code editor errors in your console window , With addition of Error Handling in Code Editor and use of dispatching errors to redux Store and would have to update console.jsx , Am i going in right direction @lindapaiste @raclim , I think adding these can solve this error if there are some suggestion please let me know and if this approach seems fine do assign me this issue i will start working on it

**Comment by lindapaiste** [comment] 2023-10-21 00:08
It is working fine for me in Windows 10 on Chrome, Firefox, Edge, and Opera.

@raclim If I have to guess, I think the issue is probably related to your note in the [fix PR](https://github.com/processing/p5.js-web-editor/pull/2507) "to address an error where the target origin does not match the recipient for the iFrame."

Another suspect would be #2426. But we've always had the console errors script running first with `head.prepend` so I don't think that's it?  https://github.com/processing/p5.js-web-editor/blob/362b5537896371542a91f68568e4d5300bc6acab/client/modules/Preview/EmbedFrame.jsx#L267

**Comment by lindapaiste** [comment] 2023-10-21 00:18
For anyone looking at this, it's honestly pretty complicated.  The user's code is executed in an iframe from preview.p5js.org.  We send messages from that frame to the editor using [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage).

The relevant code is primarily in:
https://github.com/processing/p5.js-web-editor/blob/362b5537896371542a91f68568e4d5300bc6acab/client/utils/previewEntry.js#L1-L180
https://github.com/processing/p5.js-web-editor/blob/362b5537896371542a91f68568e4d5300bc6acab/client/utils/dispatcher.js#L4-L69
https://github.com/processing/p5.js-web-editor/blob/362b5537896371542a91f68568e4d5300bc6acab/client/modules/Preview/EmbedFrame.jsx#L280-L288
https://github.com/processing/p5.js-web-editor/blob/362b5537896371542a91f68568e4d5300bc6acab/client/modules/IDE/components/PreviewFrame.jsx#L16-L22
https://github.com/processing/p5.js-web-editor/blob/362b5537896371542a91f68568e4d5300bc6acab/client/modules/IDE/components/Console.jsx#L222-L228
https://github.com/processing/p5.js-web-editor/blob/362b5537896371542a91f68568e4d5300bc6acab/client/modules/IDE/hooks/useHandleMessageEvent.js#L1-L35

(The lack of a dependency array on all of the `useEffect`s is wonky but it's not new so I doubt that's the problem)

**Comment by raclim** [comment] 2023-10-31 14:59
Hi all, I think this error should be resolved by a different @lindapaiste refers to earlier in @2426. I just reverted it in #2547 and deployed it to production just now. I think this should fix it, but please let me know if this is still happening!

**Closed as completed by raclim** 2023-10-31 14:59 UTC
Labels: Priority:High, Good Medium Issue, Bug
