### ISSUE TITLE
The end of empty element is broken

### ISSUE THREAD

**Issue by kazuhikoarase** [processing/p5.js-web-editor#1211] opened 2019-11-15 10:50 UTC
#### Nature of issue?

- Found a bug

#### Details about the bug: 

At server/views/index.js line 15, the end of empty element is broken.

```html
  <link rel='shortcut icon' ... type='image/x-icon'/ >
```
should be
```html
  <link rel='shortcut icon' ... type='image/x-icon' />
```

- Web browser and version: Microsoft Edge (I see the error message at the developer console.)
- Operating System: Windows
- Steps to reproduce this bug: run the editor

**Comment by catarak** [comment] 2019-11-20 19:48
thanks for reporting!

**Comment by zoyron** [comment] 2020-01-11 06:32
If the issue is still open and it is assigned to no one, I'd like to work on this.
Thank you.

**Comment by ani4aniket** [comment] 2020-01-12 10:32
@zoyron I have already created a PR fixing this.

**Comment by ashu8912** [comment] 2020-01-20 14:50
Hey @ani4aniket please mention your pr here so that others can get that there is already a pr regarding this.

**Closed** 2020-01-28 22:06 UTC
Labels: good first issue, help wanted, priority:medium, type:bug
