### ISSUE TITLE
lights it no define

### ISSUE THREAD

**Issue by unoudos** [processing/p5.js-web-editor#1124] opened 2019-07-29 14:51 UTC
var t;
function setup() {
  createCanvas(400, 400, WEBGL);
  lights();
}

function draw() {
  background(0); 
  clear();
  lights();
 for(let i = 0; i < 150; i++) {
    resetMatrix();
    translate(i% 10* 20 - 90, i/10 * 14 - 90, -200);
    rotateY(i * ( t += 0.000001) * PI);
    box(14);
  }
}

always say lights() it no define

**Comment by catarak** [comment] 2019-07-29 16:47
thanks for reporting! this is because the default p5.js version has not yet been updated in the web editor. this is a duplicate of #1121, so i will be closing this into that issue.

**Closed by catarak** 2019-07-29 16:47 UTC
