### ISSUE TITLE
Replacing default alert pop-up  with enhanced pop-up.

### ISSUE THREAD

**Issue by yashpandey06** [processing/p5.js-web-editor#2577] opened 2023-11-06 20:19 UTC
### Increasing Access

This feature would help increase access in the following ways:

- It will provide much better user interface experience.
- Looks more professional and will user .

### Feature enhancement details

**We are using default browser alert pop-up while creating the new file in p5 web editor , instead of this we can replace it with some enhanced designed pop-up .**

currently it is like ---->

<img width="960" alt="Screenshot 2023-11-06 234058" src="https://github.com/processing/p5.js-web-editor/assets/97700473/095f4ba6-6d05-4e21-8396-adddaa8e42c2">

**It can be made into something like this---> please see the UI (ignore the text).**

I took the below image from the issue #2574 taken issue

<img width="498" alt="demo" src="https://github.com/processing/p5.js-web-editor/assets/97700473/546b669b-4a6a-4b79-b925-09a0978b63c5">

@lindapaiste  @raclim  please have a look on this issue , would love to have your views.

**Comment by lindapaiste** [comment] 2023-11-11 01:01
I'm closing this as a duplicate of #2574 

The appearance of the default browser alerts will vary from person to person.  It depends on the browser, the browser theme, and the system light/dark settings.  This is what it looks like currently for me in Chrome

with Windows light mode:
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/343ec185-bda1-4a8e-a0e2-b7703c31e436)
with Windows dark mode:
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/f78cfa4d-d959-48f7-964f-1a42555b5a88)

**Closed as not planned** 2023-11-11 01:19 UTC
Labels: Enhancement
