### ISSUE TITLE
print() function prompts actual printing in browser

### ISSUE THREAD

**Issue by Shay-Almog** [processing/p5.js-web-editor#1978] opened 2021-11-20 14:08 UTC
Hello!

When the print() function is called without arguments it prompts the browser's Print dialogue, as if I've pressed CTRL+P.
This issue comes up while working with auto refresh turned on and the code is already running - I start typing "print(..." and the right parenthesis is auto-completed before I type in the argument. The editor the runs the unfinished line of code "print()" resulting in the browsers Print dialogue to pop up. Doing so inside the Draw loop will result in endless popping up of the Print dialogue. The only way to stop the this madness is to close the tab/window, losing any unsaved code.
This also occurs when "print()" without arguments is typed anywhere else in the code.

I am using windows 10 and this issue occurs in every browser I've tried - chrome, firefox and edge

I hope this issue could be resolved shortly!

https://user-images.githubusercontent.com/31411481/142729283-b50ee48f-1a69-406e-8c57-202dee58ed66.mp4

**Comment by stampyzfanz** [comment] 2022-01-20 05:24
Could reproduce in editor as well as in native p5.js in the browser in Chrome. That makes me think that this occurs in p5.js as a whole, not just the web editor. Additionally, it only does this with the `print()` call not `print("text")`. 

As I see it, there are 3 alternatives:
1. Works as intended
2. Does not work as intended, and create an issue in p5.js
3. Works as intended in p5.js, but is annoying in the web editor so don't automatically display the output. Although this option could lead to confusion for people intended the print dialog to appear.

**Comment by 3ru** [comment] 2022-03-10 12:07
As a [reference](https://p5js.org/reference/#/p5/print) shows, `print()` invokes the `window.print()`.

To avoid getting stuck by auto-completion, I recommend turning off `Autoclose Brackets and Quotes`.

<img src="https://i.gyazo.com/9c3d262583980e3bf868fc97719970f1.png" width=500>


I think this issue should be closed:cat: @catarak

**Comment by raclim** [comment] 2022-10-26 22:00
Hi! It seems like this issue has been resolved, so I'm going to close it. Please feel free to reopen it or create a new one if it comes up again, thanks! 🙂

**Closed as completed by raclim** 2022-10-26 22:00 UTC
