### ISSUE TITLE
editor preview is not working!

### ISSUE THREAD

**Issue by Shay-Almog** [processing/p5.js-web-editor#1966] opened 2021-11-12 12:24 UTC
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by kjhollen** [comment] 2021-11-12 16:09
Hi @Shay-Almog, thanks for reporting this. I believe this is a duplicate of #1965. I'm going to close this issue so that we can keep track of everything in just one place, but if you believe this is a different issue, please provide more information and we will re-open. Thank you!

**Closed as completed by kjhollen** 2021-11-12 16:09 UTC
