### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_report')     at undefined:2:30224

### ISSUE THREAD

**Issue by kewlfool** [processing/p5.js-web-editor#2145] opened 2023-03-03 21:24 UTC
Hi there, 

i have a p5js sketch that works fine locally, but when i copy it on web editor it dont run.

TypeError: Cannot read properties of undefined (reading '_report')
    at undefined:2:30224

**Comment by parteekcoder** [comment] 2023-03-04 13:50
Can you please give the steps to reproduce it 

And can you please also attach the screenshots for more clarity

**Comment by kewlfool** [comment] 2023-03-04 14:00
Here is the link for sketch on web editor 
https://editor.p5js.org/kewlfool/sketches/tvdNsR5H5

Also i created a repository that runs fine.

https://github.com/kewlfool/htmlJavascript

**Comment by parteekcoder** [comment] 2023-03-04 14:13
@kewlfool is it runs fine in your repository?

**Comment by kewlfool** [comment] 2023-03-04 14:18
yes it runs fine locally, 
doesnt work on web editor.

**Comment by lindapaiste** [comment] 2023-03-07 17:50
Interesting issue.  The problem here is a naming collision on `Symbol`.

Your code will work if you rename your `Symbol` class to `MySymbol` or anything else.  Your class is conflicting with the [built-in JavaScript `Symbol` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol).  Specifically, it creates trouble with the [`shim.js` file in the p5 core](https://github.com/processing/p5.js/blob/main/src/core/shim.js).

**Comment by raclim** [comment] 2023-03-15 00:17
Agreed with the above!  I think a secondary root cause of this issue stems from the `'index.html'` file in the sketch you linked for the web editor. Within that file on `line 8`, it seems like you're using p5.js version `0.5.6` instead of `1.6.0`. 

Hope this was able to resolve your issue! I'm going to close this for now, but please feel free to reopen this or create a new one if it still persists for you.

**Closed as completed by raclim** 2023-03-15 00:17 UTC
