### ISSUE TITLE
 The editor does not show any error if you write lenght instead of length in arrays

### ISSUE THREAD

**Issue by ernio** [processing/p5.js-web-editor#427] opened 2017-08-30 11:46 UTC
} else if(stack.lenght > 0) {

**Comment by catarak** [comment] 2017-11-13 21:51
The weird thing about JavaScript is that I _think_ this is technically not an error; since the property `lenght` of the variable `stack` is not defined, the expected behavior of this is that `undefined` would be printed to the console, not an error. However, undefined is not being printed to the console and i'm seeing a different error:
<img width="720" alt="screen shot 2017-11-13 at 4 50 25 pm" src="https://user-images.githubusercontent.com/6063380/32751157-d09f537a-c892-11e7-9b9a-1e53b2f500da.png">

**Comment by catarak** [comment] 2017-11-13 21:51
this may be related to #468

**Comment by himanshuc3** [comment] 2018-02-20 09:58
Probably not a feature which is implemented in codemirror!

**Comment by catarak** [comment] 2018-02-20 17:53
CodeMirror is just a text editor and isn't handling console errors, it's the console component that this is related to!

**Comment by catarak** [comment] 2018-10-25 21:45
this has been fixed with the new console implementation!

**Closed by catarak** 2018-10-25 21:45 UTC
Labels: type:bug
