### ISSUE TITLE
Viewing a Map in the console crashes the session

### ISSUE THREAD

**Issue by Dollar-500** [processing/p5.js-web-editor#1088] opened 2019-05-29 22:18 UTC
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome Version 74.0.3729.169
- Operating System: Windows
- Steps to reproduce this bug: 
-- Copy and paste the linked code into the web editor
-- Open up the console
-- Click the disclosure triangle on the Map object that was printed

Here is the code (it's short, don't worry): https://pastebin.com/WWCC0yqu

Here is the window + dev tools window *before* I clicked the disclosure triangle:
<img width="960" alt="BeforeClick" src="https://user-images.githubusercontent.com/39846627/58595211-805d8180-8235-11e9-8621-8b90750e1740.PNG">

Here is the window + dev tools window *after* I clicked the disclosure triangle:
<img width="959" alt="AfterClick" src="https://user-images.githubusercontent.com/39846627/58595212-84899f00-8235-11e9-968b-ade5e5566d9d.PNG">

**Comment by catarak** [comment] 2019-05-31 15:20
thanks for reporting!

**Comment by catarak** [comment] 2019-05-31 15:32
i tried running this locally to get better errors, and this is what i'm seeing:
```
checkPropTypes.js?21ee:20 Warning: Failed prop type: Invalid prop `name` of type `object` supplied to `ConnectedTreeNode`, expected `string`.
    in ConnectedTreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by TreeView)
    in TreeView (created by ObjectInspector)
    in ThemeProvider (created by ObjectInspector)
    in ObjectInspector (created by Inspector)
    in Inspector (created by CustomInspector)
    in div (created by Styled(div))
    in Styled(div) (created by CustomInspector)
    in CustomInspector (created by WithTheme(CustomInspector))
    in WithTheme(CustomInspector) (created by ObjectTree)
    in ObjectTree (created by WithTheme(ObjectTree))
    in WithTheme(ObjectTree) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in ThemeProvider (created by ConsoleMessage)
    in ConsoleMessage (created by Console)
    in div (created by Styled(div))
    in Styled(div) (created by Console)
    in ThemeProvider (created by Console)
    in Console (created by Console)
    in div (created by Console)
    in div (created by Console)
    in div (created by Console)
    in Console (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by IDEView)
    in div (created by IDEView)
    in IDEView (created by Connect(IDEView))
    in Connect(IDEView) (created by withRouter(Connect(IDEView)))
    in withRouter(Connect(IDEView)) (created by RouterContext)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
printWarning @ checkPropTypes.js?21ee:20
checkPropTypes @ checkPropTypes.js?21ee:82
validatePropTypes @ react.development.js?99ee:1666
createElementWithValidation @ react.development.js?99ee:1755
React$$1.createElement @ react-hot-loader.development.js?280f:2442
renderChildNodes @ TreeView.js?83f2:116
onStateChange @ react-hot-loader.development.js?280f:652
render @ TreeView.js?83f2:175
finishClassComponent @ react-dom.development.js?cada:14537
updateClassComponent @ react-dom.development.js?cada:14492
beginWork @ react-dom.development.js?cada:15440
performUnitOfWork @ react-dom.development.js?cada:19108
workLoop @ react-dom.development.js?cada:19148
renderRoot @ react-dom.development.js?cada:19231
performWorkOnRoot @ react-dom.development.js?cada:20138
performWork @ react-dom.development.js?cada:20050
performSyncWork @ react-dom.development.js?cada:20024
interactiveUpdates$1 @ react-dom.development.js?cada:20291
interactiveUpdates @ react-dom.development.js?cada:2170
dispatchInteractiveEvent @ react-dom.development.js?cada:4882
checkPropTypes.js?21ee:20 Warning: Failed prop type: Invalid prop `name` of type `object` supplied to `TreeNode`, expected `string`.
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by ConnectedTreeNode)
    in ol (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by TreeView)
    in TreeView (created by ObjectInspector)
    in ThemeProvider (created by ObjectInspector)
    in ObjectInspector (created by Inspector)
    in Inspector (created by CustomInspector)
    in div (created by Styled(div))
    in Styled(div) (created by CustomInspector)
    in CustomInspector (created by WithTheme(CustomInspector))
    in WithTheme(CustomInspector) (created by ObjectTree)
    in ObjectTree (created by WithTheme(ObjectTree))
    in WithTheme(ObjectTree) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in ThemeProvider (created by ConsoleMessage)
    in ConsoleMessage (created by Console)
    in div (created by Styled(div))
    in Styled(div) (created by Console)
    in ThemeProvider (created by Console)
    in Console (created by Console)
    in div (created by Console)
    in div (created by Console)
    in div (created by Console)
    in Console (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by IDEView)
    in div (created by IDEView)
    in IDEView (created by Connect(IDEView))
    in Connect(IDEView) (created by withRouter(Connect(IDEView)))
    in withRouter(Connect(IDEView)) (created by RouterContext)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
printWarning @ checkPropTypes.js?21ee:20
checkPropTypes @ checkPropTypes.js?21ee:82
validatePropTypes @ react.development.js?99ee:1666
createElementWithValidation @ react.development.js?99ee:1755
React$$1.createElement @ react-hot-loader.development.js?280f:2442
render @ TreeView.js?83f2:162
finishClassComponent @ react-dom.development.js?cada:14537
updateClassComponent @ react-dom.development.js?cada:14492
beginWork @ react-dom.development.js?cada:15440
performUnitOfWork @ react-dom.development.js?cada:19108
workLoop @ react-dom.development.js?cada:19148
renderRoot @ react-dom.development.js?cada:19231
performWorkOnRoot @ react-dom.development.js?cada:20138
performWork @ react-dom.development.js?cada:20050
performSyncWork @ react-dom.development.js?cada:20024
interactiveUpdates$1 @ react-dom.development.js?cada:20291
interactiveUpdates @ react-dom.development.js?cada:2170
dispatchInteractiveEvent @ react-dom.development.js?cada:4882
checkPropTypes.js?21ee:20 Warning: Failed prop type: Invalid prop `name` of type `object` supplied to `ObjectName`, expected `string`.
    in ObjectName (created by ObjectLabel)
    in ObjectLabel (created by bound )
    in bound  (created by TreeNode)
    in div (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by ConnectedTreeNode)
    in ol (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by TreeView)
    in TreeView (created by ObjectInspector)
    in ThemeProvider (created by ObjectInspector)
    in ObjectInspector (created by Inspector)
    in Inspector (created by CustomInspector)
    in div (created by Styled(div))
    in Styled(div) (created by CustomInspector)
    in CustomInspector (created by WithTheme(CustomInspector))
    in WithTheme(CustomInspector) (created by ObjectTree)
    in ObjectTree (created by WithTheme(ObjectTree))
    in WithTheme(ObjectTree) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in ThemeProvider (created by ConsoleMessage)
    in ConsoleMessage (created by Console)
    in div (created by Styled(div))
    in Styled(div) (created by Console)
    in ThemeProvider (created by Console)
    in Console (created by Console)
    in div (created by Console)
    in div (created by Console)
    in div (created by Console)
    in Console (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by IDEView)
    in div (created by IDEView)
    in IDEView (created by Connect(IDEView))
    in Connect(IDEView) (created by withRouter(Connect(IDEView)))
    in withRouter(Connect(IDEView)) (created by RouterContext)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
printWarning @ checkPropTypes.js?21ee:20
checkPropTypes @ checkPropTypes.js?21ee:82
validatePropTypes @ react.development.js?99ee:1666
createElementWithValidation @ react.development.js?99ee:1755
React$$1.createElement @ react-hot-loader.development.js?280f:2442
ObjectLabel @ ObjectLabel.js?338e:38
ObjectLabel @ react-hot-loader.development.js?280f:757
renderWithHooks @ react-dom.development.js?cada:12839
mountIndeterminateComponent @ react-dom.development.js?cada:14816
beginWork @ react-dom.development.js?cada:15421
performUnitOfWork @ react-dom.development.js?cada:19108
workLoop @ react-dom.development.js?cada:19148
renderRoot @ react-dom.development.js?cada:19231
performWorkOnRoot @ react-dom.development.js?cada:20138
performWork @ react-dom.development.js?cada:20050
performSyncWork @ react-dom.development.js?cada:20024
interactiveUpdates$1 @ react-dom.development.js?cada:20291
interactiveUpdates @ react-dom.development.js?cada:2170
dispatchInteractiveEvent @ react-dom.development.js?cada:4882
react-dom.development.js?cada:55 Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {data, constructor}). If you meant to render a collection of children, use an array instead.
    in span (created by ObjectName)
    in ObjectName (created by ObjectLabel)
    in span (created by ObjectLabel)
    in ObjectLabel (created by bound )
    in bound  (created by TreeNode)
    in div (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by ConnectedTreeNode)
    in ol (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by TreeView)
    in TreeView (created by ObjectInspector)
    in ThemeProvider (created by ObjectInspector)
    in ObjectInspector (created by Inspector)
    in Inspector (created by CustomInspector)
    in div (created by Styled(div))
    in Styled(div) (created by CustomInspector)
    in CustomInspector (created by WithTheme(CustomInspector))
    in WithTheme(CustomInspector) (created by ObjectTree)
    in ObjectTree (created by WithTheme(ObjectTree))
    in WithTheme(ObjectTree) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in ThemeProvider (created by ConsoleMessage)
    in ConsoleMessage (created by Console)
    in div (created by Styled(div))
    in Styled(div) (created by Console)
    in ThemeProvider (created by Console)
    in Console (created by Console)
    in div (created by Console)
    in div (created by Console)
    in div (created by Console)
    in Console (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by IDEView)
    in div (created by IDEView)
    in IDEView (created by Connect(IDEView))
    in Connect(IDEView) (created by withRouter(Connect(IDEView)))
    in withRouter(Connect(IDEView)) (created by RouterContext)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
    at invariant (webpack-internal:///353:55:15)
    at throwOnInvalidObjectType (webpack-internal:///353:11784:5)
    at reconcileChildFibers (webpack-internal:///353:12558:7)
    at reconcileChildren (webpack-internal:///353:14198:28)
    at updateHostComponent (webpack-internal:///353:14659:3)
    at beginWork (webpack-internal:///353:15445:14)
    at performUnitOfWork (webpack-internal:///353:19108:12)
    at workLoop (webpack-internal:///353:19148:24)
    at HTMLUnknownElement.callCallback (webpack-internal:///353:149:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///353:199:16)
invariant @ react-dom.development.js?cada:55
throwOnInvalidObjectType @ react-dom.development.js?cada:11784
reconcileChildFibers @ react-dom.development.js?cada:12558
reconcileChildren @ react-dom.development.js?cada:14198
updateHostComponent @ react-dom.development.js?cada:14659
beginWork @ react-dom.development.js?cada:15445
performUnitOfWork @ react-dom.development.js?cada:19108
workLoop @ react-dom.development.js?cada:19148
callCallback @ react-dom.development.js?cada:149
invokeGuardedCallbackDev @ react-dom.development.js?cada:199
invokeGuardedCallback @ react-dom.development.js?cada:256
replayUnitOfWork @ react-dom.development.js?cada:18374
renderRoot @ react-dom.development.js?cada:19264
performWorkOnRoot @ react-dom.development.js?cada:20138
performWork @ react-dom.development.js?cada:20050
performSyncWork @ react-dom.development.js?cada:20024
interactiveUpdates$1 @ react-dom.development.js?cada:20291
interactiveUpdates @ react-dom.development.js?cada:2170
dispatchInteractiveEvent @ react-dom.development.js?cada:4882
react-dom.development.js?cada:16913 The above error occurred in the <span> component:
    in span (created by ObjectName)
    in ObjectName (created by ObjectLabel)
    in span (created by ObjectLabel)
    in ObjectLabel (created by bound )
    in bound  (created by TreeNode)
    in div (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by ConnectedTreeNode)
    in ol (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by TreeView)
    in TreeView (created by ObjectInspector)
    in ThemeProvider (created by ObjectInspector)
    in ObjectInspector (created by Inspector)
    in Inspector (created by CustomInspector)
    in div (created by Styled(div))
    in Styled(div) (created by CustomInspector)
    in CustomInspector (created by WithTheme(CustomInspector))
    in WithTheme(CustomInspector) (created by ObjectTree)
    in ObjectTree (created by WithTheme(ObjectTree))
    in WithTheme(ObjectTree) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in ThemeProvider (created by ConsoleMessage)
    in ConsoleMessage (created by Console)
    in div (created by Styled(div))
    in Styled(div) (created by Console)
    in ThemeProvider (created by Console)
    in Console (created by Console)
    in div (created by Console)
    in div (created by Console)
    in div (created by Console)
    in Console (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by IDEView)
    in div (created by IDEView)
    in IDEView (created by Connect(IDEView))
    in Connect(IDEView) (created by withRouter(Connect(IDEView)))
    in withRouter(Connect(IDEView)) (created by RouterContext)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ react-dom.development.js?cada:16913
logError @ react-dom.development.js?cada:16949
callback @ react-dom.development.js?cada:17890
callCallback @ react-dom.development.js?cada:16229
commitUpdateEffects @ react-dom.development.js?cada:16268
commitUpdateQueue @ react-dom.development.js?cada:16259
commitLifeCycles @ react-dom.development.js?cada:17160
commitAllLifeCycles @ react-dom.development.js?cada:18532
callCallback @ react-dom.development.js?cada:149
invokeGuardedCallbackDev @ react-dom.development.js?cada:199
invokeGuardedCallback @ react-dom.development.js?cada:256
commitRoot @ react-dom.development.js?cada:18744
(anonymous) @ react-dom.development.js?cada:20214
unstable_runWithPriority @ scheduler.development.js?767c:255
completeRoot @ react-dom.development.js?cada:20213
performWorkOnRoot @ react-dom.development.js?cada:20142
performWork @ react-dom.development.js?cada:20050
performSyncWork @ react-dom.development.js?cada:20024
interactiveUpdates$1 @ react-dom.development.js?cada:20291
interactiveUpdates @ react-dom.development.js?cada:2170
dispatchInteractiveEvent @ react-dom.development.js?cada:4882
react-hot-loader.development.js?280f:232 Invariant Violation: Objects are not valid as a React child (found: object with keys {data, constructor}). If you meant to render a collection of children, use an array instead.
    in span (created by ObjectName)
    in ObjectName (created by ObjectLabel)
    in span (created by ObjectLabel)
    in ObjectLabel (created by bound )
    in bound  (created by TreeNode)
    in div (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by ConnectedTreeNode)
    in ol (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by TreeView)
    in TreeView (created by ObjectInspector)
    in ThemeProvider (created by ObjectInspector)
    in ObjectInspector (created by Inspector)
    in Inspector (created by CustomInspector)
    in div (created by Styled(div))
    in Styled(div) (created by CustomInspector)
    in CustomInspector (created by WithTheme(CustomInspector))
    in WithTheme(CustomInspector) (created by ObjectTree)
    in ObjectTree (created by WithTheme(ObjectTree))
    in WithTheme(ObjectTree) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in ThemeProvider (created by ConsoleMessage)
    in ConsoleMessage (created by Console)
    in div (created by Styled(div))
    in Styled(div) (created by Console)
    in ThemeProvider (created by Console)
    in Console (created by Console)
    in div (created by Console)
    in div (created by Console)
    in div (created by Console)
    in Console (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by IDEView)
    in div (created by IDEView)
    in IDEView (created by Connect(IDEView))
    in Connect(IDEView) (created by withRouter(Connect(IDEView)))
    in withRouter(Connect(IDEView)) (created by RouterContext)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
    at invariant (webpack-internal:///353:55:15)
    at throwOnInvalidObjectType (webpack-internal:///353:11784:5)
    at reconcileChildFibers (webpack-internal:///353:12558:7)
    at reconcileChildren (webpack-internal:///353:14198:28)
    at updateHostComponent (webpack-internal:///353:14659:3)
    at beginWork (webpack-internal:///353:15445:14)
    at performUnitOfWork (webpack-internal:///353:19108:12)
    at workLoop (webpack-internal:///353:19148:24)
    at renderRoot (webpack-internal:///353:19231:7)
    at performWorkOnRoot (webpack-internal:///353:20138:7)
error @ react-hot-loader.development.js?280f:232
componentDidCatch @ react-hot-loader.development.js?280f:2138
callback @ react-dom.development.js?cada:17891
callCallback @ react-dom.development.js?cada:16229
commitUpdateEffects @ react-dom.development.js?cada:16268
commitUpdateQueue @ react-dom.development.js?cada:16259
commitLifeCycles @ react-dom.development.js?cada:17160
commitAllLifeCycles @ react-dom.development.js?cada:18532
callCallback @ react-dom.development.js?cada:149
invokeGuardedCallbackDev @ react-dom.development.js?cada:199
invokeGuardedCallback @ react-dom.development.js?cada:256
commitRoot @ react-dom.development.js?cada:18744
(anonymous) @ react-dom.development.js?cada:20214
unstable_runWithPriority @ scheduler.development.js?767c:255
completeRoot @ react-dom.development.js?cada:20213
performWorkOnRoot @ react-dom.development.js?cada:20142
performWork @ react-dom.development.js?cada:20050
performSyncWork @ react-dom.development.js?cada:20024
interactiveUpdates$1 @ react-dom.development.js?cada:20291
interactiveUpdates @ react-dom.development.js?cada:2170
dispatchInteractiveEvent @ react-dom.development.js?cada:4882
react-hot-loader.development.js?280f:2145 Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {data, constructor}). If you meant to render a collection of children, use an array instead.
    in span (created by ObjectName)
    in ObjectName (created by ObjectLabel)
    in span (created by ObjectLabel)
    in ObjectLabel (created by bound )
    in bound  (created by TreeNode)
    in div (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by ConnectedTreeNode)
    in ol (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by TreeView)
    in TreeView (created by ObjectInspector)
    in ThemeProvider (created by ObjectInspector)
    in ObjectInspector (created by Inspector)
    in Inspector (created by CustomInspector)
    in div (created by Styled(div))
    in Styled(div) (created by CustomInspector)
    in CustomInspector (created by WithTheme(CustomInspector))
    in WithTheme(CustomInspector) (created by ObjectTree)
    in ObjectTree (created by WithTheme(ObjectTree))
    in WithTheme(ObjectTree) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in ThemeProvider (created by ConsoleMessage)
    in ConsoleMessage (created by Console)
    in div (created by Styled(div))
    in Styled(div) (created by Console)
    in ThemeProvider (created by Console)
    in Console (created by Console)
    in div (created by Console)
    in div (created by Console)
    in div (created by Console)
    in Console (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by IDEView)
    in div (created by IDEView)
    in IDEView (created by Connect(IDEView))
    in Connect(IDEView) (created by withRouter(Connect(IDEView)))
    in withRouter(Connect(IDEView)) (created by RouterContext)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
    at invariant (webpack-internal:///353:55:15)
    at throwOnInvalidObjectType (webpack-internal:///353:11784:5)
    at reconcileChildFibers (webpack-internal:///353:12558:7)
    at reconcileChildren (webpack-internal:///353:14198:28)
    at updateHostComponent (webpack-internal:///353:14659:3)
    at beginWork (webpack-internal:///353:15445:14)
    at performUnitOfWork (webpack-internal:///353:19108:12)
    at workLoop (webpack-internal:///353:19148:24)
    at renderRoot (webpack-internal:///353:19231:7)
    at performWorkOnRoot (webpack-internal:///353:20138:7)
invariant @ react-dom.development.js?cada:55
throwOnInvalidObjectType @ react-dom.development.js?cada:11784
reconcileChildFibers @ react-dom.development.js?cada:12558
reconcileChildren @ react-dom.development.js?cada:14198
updateHostComponent @ react-dom.development.js?cada:14659
beginWork @ react-dom.development.js?cada:15445
performUnitOfWork @ react-dom.development.js?cada:19108
workLoop @ react-dom.development.js?cada:19148
renderRoot @ react-dom.development.js?cada:19231
performWorkOnRoot @ react-dom.development.js?cada:20138
performWork @ react-dom.development.js?cada:20050
performSyncWork @ react-dom.development.js?cada:20024
interactiveUpdates$1 @ react-dom.development.js?cada:20291
interactiveUpdates @ react-dom.development.js?cada:2170
dispatchInteractiveEvent @ react-dom.development.js?cada:4882
react-dom.development.js?cada:16913 The above error occurred in the <AppContainer> component:
    in AppContainer (created by HotExportedApp)
    in HotExportedApp

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js?cada:16913
logError @ react-dom.development.js?cada:16949
update.callback @ react-dom.development.js?cada:17861
callCallback @ react-dom.development.js?cada:16229
commitUpdateEffects @ react-dom.development.js?cada:16268
commitUpdateQueue @ react-dom.development.js?cada:16256
commitLifeCycles @ react-dom.development.js?cada:17179
commitAllLifeCycles @ react-dom.development.js?cada:18532
callCallback @ react-dom.development.js?cada:149
invokeGuardedCallbackDev @ react-dom.development.js?cada:199
invokeGuardedCallback @ react-dom.development.js?cada:256
commitRoot @ react-dom.development.js?cada:18744
(anonymous) @ react-dom.development.js?cada:20214
unstable_runWithPriority @ scheduler.development.js?767c:255
completeRoot @ react-dom.development.js?cada:20213
performWorkOnRoot @ react-dom.development.js?cada:20142
performWork @ react-dom.development.js?cada:20050
performSyncWork @ react-dom.development.js?cada:20024
interactiveUpdates$1 @ react-dom.development.js?cada:20291
interactiveUpdates @ react-dom.development.js?cada:2170
dispatchInteractiveEvent @ react-dom.development.js?cada:4882
react-dom.development.js?cada:55 Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {data, constructor}). If you meant to render a collection of children, use an array instead.
    in span (created by ObjectName)
    in ObjectName (created by ObjectLabel)
    in span (created by ObjectLabel)
    in ObjectLabel (created by bound )
    in bound  (created by TreeNode)
    in div (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by ConnectedTreeNode)
    in ol (created by TreeNode)
    in li (created by TreeNode)
    in TreeNode (created by ConnectedTreeNode)
    in ConnectedTreeNode (created by TreeView)
    in TreeView (created by ObjectInspector)
    in ThemeProvider (created by ObjectInspector)
    in ObjectInspector (created by Inspector)
    in Inspector (created by CustomInspector)
    in div (created by Styled(div))
    in Styled(div) (created by CustomInspector)
    in CustomInspector (created by WithTheme(CustomInspector))
    in WithTheme(CustomInspector) (created by ObjectTree)
    in ObjectTree (created by WithTheme(ObjectTree))
    in WithTheme(ObjectTree) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in div (created by Styled(div))
    in Styled(div) (created by ConsoleMessage)
    in ThemeProvider (created by ConsoleMessage)
    in ConsoleMessage (created by Console)
    in div (created by Styled(div))
    in Styled(div) (created by Console)
    in ThemeProvider (created by Console)
    in Console (created by Console)
    in div (created by Console)
    in div (created by Console)
    in div (created by Console)
    in Console (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by IDEView)
    in div (created by IDEView)
    in div (created by IDEView)
    in IDEView (created by Connect(IDEView))
    in Connect(IDEView) (created by withRouter(Connect(IDEView)))
    in withRouter(Connect(IDEView)) (created by RouterContext)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by App)
    in Provider (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
    at invariant (webpack-internal:///353:55:15)
    at throwOnInvalidObjectType (webpack-internal:///353:11784:5)
    at reconcileChildFibers (webpack-internal:///353:12558:7)
    at reconcileChildren (webpack-internal:///353:14198:28)
    at updateHostComponent (webpack-internal:///353:14659:3)
    at beginWork (webpack-internal:///353:15445:14)
    at performUnitOfWork (webpack-internal:///353:19108:12)
    at workLoop (webpack-internal:///353:19148:24)
    at renderRoot (webpack-internal:///353:19231:7)
    at performWorkOnRoot (webpack-internal:///353:20138:7)
invariant @ react-dom.development.js?cada:55
throwOnInvalidObjectType @ react-dom.development.js?cada:11784
reconcileChildFibers @ react-dom.development.js?cada:12558
reconcileChildren @ react-dom.development.js?cada:14198
updateHostComponent @ react-dom.development.js?cada:14659
beginWork @ react-dom.development.js?cada:15445
performUnitOfWork @ react-dom.development.js?cada:19108
workLoop @ react-dom.development.js?cada:19148
renderRoot @ react-dom.development.js?cada:19231
performWorkOnRoot @ react-dom.development.js?cada:20138
performWork @ react-dom.development.js?cada:20050
performSyncWork @ react-dom.development.js?cada:20024
interactiveUpdates$1 @ react-dom.development.js?cada:20291
interactiveUpdates @ react-dom.development.js?cada:2170
dispatchInteractiveEvent @ react-dom.development.js?cada:4882
```

**Comment by bomoko** [comment] 2019-07-31 05:08
I'm digging into this as a way of getting my head around the IDE code itself.

It turns out that the problem isn't printing a Map _per se_ but rather using the map in the way that it's being used in the example - in the example we're mapping an _object_ as a key (any object as key seems to do it - and it deals with objects as values no problem).
Maps with simple types as keys seem to work no problem.

Now, as for where the problem actually _lies_ it turns out that it's not in the web editor either - it's in the console-feed package we're pulling in (https://www.npmjs.com/package/console-feed). *_That's_* what's crashing - and when it is, React is unmounting the whole editor.

One option to address this inside the editor for now is to follow https://flaviocopes.com/react-handle-errors/ and implement an error boundary wrapping the console component and providing some kind of reasonable default behaviour that doesn't crash the entire editor.

I'm going to open a PR as an example of this (it fixes the crash that we're seeing) - it's a POC and WIP. If we want to develop it further I'd be happy to, I'm new around these parts and would love to contribute (with some guidance)

**Comment by catarak** [comment] 2019-07-31 18:18
@bomoko glad to have you working on this! i had noticed some issues with the console when I was working on merging in #667, but i haven't had a chance to pick that work back up again. i'll take a look at your PR!

**Comment by catarak** [comment] 2020-02-04 22:14
just tested this again, and it seems like this is no longer happening. closing!

**Closed by catarak** 2020-02-04 22:14 UTC
Labels: help wanted, priority:medium, type:bug
