### ISSUE TITLE
npm install errors - v10.1.0 compatibility problem?

### ISSUE THREAD

**Issue by awarua** [processing/p5.js-web-editor#640] opened 2018-05-20 00:34 UTC
#### Nature of issue?

- [X ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Operating System: MacOSX 10.13.4
- node version: v10.1.0
- Steps to reproduce this:
``` sh
$ git clone git@github.com:processing/p5.js-web-editor.git
$ cd p5.js-web-editor.git
$ npm install
```

When I follow the installation instructions above (from the README), the npm installation fails with the following error (this is an extract of a much longer output): 

```sh
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'mkdirp'
```

I then try installing that module manually with `npm i mkdirp`, which leads to similar error for the `inherits` module. After that, I get an error for the `once` module. Then `inherits` again.

I'm not too familiar with npm/node, so maybe I'm doing something fundamentally wrong. I'm just trying to follow the README instructions.

**Comment by awarua** [comment] 2018-05-20 00:54
I kept adding modules to the command line until it finally installed. This is what I ended up using:
```sh
$ npm install inherits  core-util-is once pinkie-promise string-width object-assign strip-ansi which
$ npm install
```

**Comment by catarak** [comment] 2018-05-20 05:11
i'm not sure what the issue is, but there seems to be a problem with `package-lock.json`. i ran into this and i was able to fix it by removing `package-lock.json` and then running `npm install` again. Also, I'm using node 8.11.1.

**Comment by awarua** [comment] 2018-05-20 07:42
A further update. Although the `npm install` command was able to complete above, when I tried to run the server, it had an error.

I tried downgrading to node v8.11.2 with `brew install node@8` and it worked. So it seems like this might be a compatibility problem with the latest version of node? I will update the title of the issue to reflect this.

**Comment by catarak** [comment] 2018-05-20 17:52
i think there's also a bigger question here, which is how to handle enforcing contributors to use a certain node version (maybe just using Docker?) or how to handle different versions of node?

**Comment by shinytang6** [comment] 2018-05-21 16:08
I also encountered installation problems, maybe we should add `package-lock.json` to `.gitignore`?

**Comment by catarak** [comment] 2018-05-24 20:43
i think if `package-lock.json` is functioning properly it's supposed to be checked in. i ran into a really similar issue on a separate project i was woking on (unfortunately it's a private repo) and we fixed it by switching from npm to yarn. maybe that's the thing to do? i think there's some research to do.

**Comment by awarua** [comment] 2018-06-08 10:09
@catarak - while we figure out the best solution to guarantee the node version contributors are using, would it be worthwhile adding a note to the README to let people know that they need to be on node 8?

**Comment by catarak** [comment] 2018-06-08 20:13
sure! i don't know if `engines` in `package.json` actually does anything, but that could be updated too. on a separate branch, not merged to master but currently pushed to github called `production-docker`, i'm working on ironing out the details on a development and production Docker setup which also helps with this.

**Comment by catarak** [comment] 2018-10-22 22:12
i'm not able to reproduce error (just tried changing my node version and it was totally fine), so i'm going to close this ticket.

**Closed by catarak** 2018-10-22 22:12 UTC
