### ISSUE TITLE
Performance issue in web editor (frame freezing every second or so)

### ISSUE THREAD

**Issue by EthanHermsey** [processing/p5.js-web-editor#714] opened 2018-10-04 14:31 UTC
Hello!

Since the editor stepped out of the alpha stage I have this weird performance issue.

With all sketches, even the most simple sketches, the editor kind of hangs and freezes every second of so. I only have this in the editor itself, when I open the same sketch 'fullscreen' (with the link in the share menu) it works fine. 

I'm using chrome on a window 7 machine. I've attached a performance profile recording of 10 second. it completely freezes when I try to record that, but maybe it helps clearing stuff up? 

I've searched for the issue but did not find a comparable one.

Kind regards,
Ethan.

[Performance-Profile.zip](https://github.com/processing/p5.js-web-editor/files/2446694/Performance-Profile.zip)

**Comment by catarak** [comment] 2018-10-04 18:33
thanks for reporting! the main difference between alpha vs the current release is in the hosting (i moved the app from an AWS EC2 instance to a Kubernetes cluster), so i don't think this would affect the performance in the browser. 

i'm not super knowledgeable on making JS in the browser for performant tbh, so as much help as possible on that front would be great!

also, since this has come up a few times, could you try running the app in an incognito window? some folks have reported issues and then realized it was a problem with extensions.

**Comment by EthanHermsey** [comment] 2018-10-04 23:07
You know what.. That does make a difference, in incognito mode the editor works fine. 

I've tried disabling all my extensions, but that does not help. Is it the fact that they are installed?
I know the only thing I added recently is a developertools theme (accompanied by a chrome flag). I uninstalled that and referred the chrome flag, but that does not help.
What would you suggest? :s

Also, isn't it strange that it doesn't interfere in fullscreen mode?

Thanks in advance for the attention to this issue.

**Comment by catarak** [comment] 2018-10-25 21:06
closing this, as it seems unclear where the issue is here. feel free to reopen if it comes up again or is a major blocker!

**Closed by catarak** 2018-10-25 21:06 UTC

**Comment by LeroySalih** [comment] 2019-01-20 15:48
I've also hit this issue.  Very poor performance when running in Chrome, mac osx.  But for me, the difference is whether I'm logged in or not.

If I log out and run the following sketch by pasting the URL

https://editor.p5js.org/LeroySalih/sketches/HyjSeBiJN

The sketch runs perfectly.

If I then log in, and re-run the sketch,  performance drops dramatically.    This happens whether I'm in incognito mode or not.

**Comment by catarak** [comment] 2019-01-25 19:14
i'm thinking this maybe has to do with the accessibility features being turned on. it seems like a lot of folks are accidentally turning them on and seeing strange behavior.
