### ISSUE TITLE
Need to be able to check rev of p5.js in Web Editor and elsewhere

### ISSUE THREAD

**Issue by grege2** [processing/p5.js-web-editor#828] opened 2019-02-11 20:19 UTC
#### Nature of issue?

- New feature request

#### New feature details:

The issue https://github.com/processing/p5.js/issues/3512 shows a case where it is quite misleading checking something in the Web Editor, without knowing what release of p5.js it is running.

I had this problem myself (ie. not knowing the rev behind the web editor) in a recent issue https://github.com/processing/p5.js/issues/3490

I proposed that the rev of p5.js should be queryable in an old Issue https://github.com/processing/p5.js/issues/2525 but it was closed due to general lack of momentum, that's ok, I didn't push it very hard myself.

I'd like to re-open the idea of being able to check the release of p5.js from your code. 

Cheers, Greg E

**Comment by hellonearthis** [comment] 2019-02-12 15:32
Opening the index.html will show you the p5 version being used and you can change that to a newer version if you desire.
<img width="1386" alt="screenshot_19" src="https://user-images.githubusercontent.com/121805/52646844-662eba80-2f48-11e9-8dfa-a54ea14d9c9d.png">

**Comment by grege2** [comment] 2019-02-12 19:45
Thanks for that, I didn't know you could check index.html in the Web Editor. The current version is certainly running 0.7.2

![webeditrev](https://user-images.githubusercontent.com/33416604/52662473-68007a00-2f58-11e9-9d65-ebc1f190d72e.png)

There are other cases where you can't easily check this, eg. openprocessing.org, where the p5.js lib is buried in a huge framework, I was never able to find it.

I also think it's useful to be able to check it programmatically. I'm sending code to some collaborators using a local copy of p5.js and  I can't easily enforce what they're using, or that they have updated promptly when a new rev is available.

I don't advocate convoluted "get-around" coding around versions of libraries, but sometimes a check would be very useful for an important feature that just won't work in an older release, or has been broken in a new release. And if the sketch code discovers that it's running on a very old rev, it could perhaps just error and quit.

All this seemed to be accepted in discussion in processing/p5.js#2525 but it lost momentum and got closed, that's ok.

Ciao e buona fortuna a tutti.

**Comment by catarak** [comment] 2019-02-20 20:20
hi @grege2! thanks for making this issue. i think this could be partially covered in the web editor, and partially in the p5 library itself. getting p5 to return its version number would be handled in the library. however, one feature we've been wanted to add to the web editor is library management, see #4, which i think would also help with this.

**Comment by catarak** [comment] 2019-02-25 21:57
i'm going to close this issue as it's a duplicate of #4 and also #144, and your other suggestion should be put into the p5.js library itself.

**Closed by catarak** 2019-02-25 21:57 UTC

**Comment by grege2** [comment] 2019-02-26 08:18
Hi @catarak  - that's fine to close this issue in the p5 web editor list. What do you think I should do about progressing it in p5.js ?

**Comment by catarak** [comment] 2019-02-26 22:25
i just took a look at the ticket you made in the p5 repository (processing/p5.js#2525)—if you think it's important, feel free to reopen it! i recommend adding some use cases and some examples of libraries that add this behavior, as it will help determine how high priority it is with respect to other open tickets.

**Comment by grege2** [comment] 2019-02-27 02:53
Hi @catarak. Thanks. I'll look around, and maybe submit an implementation as well. Always easier to approve a mod/PR that's already been solved :=) Ciao.
