### ISSUE TITLE
MouseX, MouseY not working 

### ISSUE THREAD

**Issue by Typicalcodes** [processing/p5.js-web-editor#2506] opened 2023-10-16 12:38 UTC
### p5.js version

V2.7.3

### What is your operating system?

None

### Web browser and version

1.59.117 Chromium: 118.0.5993.70 (Official Build) (64-bit)

### Actual Behavior

I am running p5js in through Docker Installation. Other things are running fine but When I write MouseX, MouseY in Ellipse it is moving to top left corner. 
In video First I am running official p5js and then I am showing it in my local environment.

https://github.com/processing/p5.js-web-editor/assets/100959820/f6df0a25-1ac6-4ba4-8fd5-5a72d5fa46e1

### Expected Behavior

Expected behavior is movement of ellipse with the cursor while making coppies.

### Steps:
1. Forked p5 repo and cloned it 
2. Follow docker installation of p5 js on windows 
3. Open localhost:8000

**Comment by ayeshag7** [comment] 2023-10-17 17:42
Can I work on this issue?

**Comment by lindapaiste** [comment] 2023-10-17 17:54
Good catch!  I think the source of the problem is what I described here: https://github.com/processing/p5.js-web-editor/pull/2507#issuecomment-1766783635

**Comment by raclim** [comment] 2023-10-18 21:03
Hopefully this should now be resolved with the [new release](https://github.com/processing/p5.js-web-editor/releases/tag/v2.8.0), so I'm going to close this for now! Please feel free to reopen this or create a new issue if it persists!

**Closed as completed by raclim** 2023-10-18 21:03 UTC
Labels: Bug
