### ISSUE TITLE
Grayscale fill() or background() with alpha crashes sketch

### ISSUE THREAD

**Issue by itsjoel** [processing/p5.js-web-editor#590] opened 2018-03-02 22:19 UTC
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: 64.0.3282.186 (Official Build) (64-bit) (cohort: Stable)
- Operating System: Windows 10 1709
- Steps to reproduce this:

```javascript
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(0, 10);
}
```

```javascript
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(0);
  fill(255, 255)
  ellipse(mouseX, mouseY, 10, 10)
}
```
After a few frames, the sketch stops working (it freezes) and I get `Script error. (: line 0)` in the console. This only happens in Editor mode, in Fullscreen mode, it works fine. This even happens when the alpha value is 255 or 0.

**Comment by itsjoel** [comment] 2018-03-02 22:24
Realized this happens for `fill()` too.

**Comment by catarak** [comment] 2018-03-02 23:18
thanks for submitting this! i'm not able to reproduce. would you mind opening up the chrome developer tools and seeing if there are any errors in there?

**Comment by itsjoel** [comment] 2018-03-02 23:24
In dev tools I'm getting this error:
```
Uncaught TypeError: Cannot read property 'color' of undefined
    at BackgroundEntity.populate (https://cdn.rawgit.com/MathuraMG/p5-accessibility/298ccdf6/dist/p5-accessibility.js:1059:68)
    at new BackgroundEntity (https://cdn.rawgit.com/MathuraMG/p5-accessibility/298ccdf6/dist/p5-accessibility.js:1062:8)
    at gridInterceptor.populateObject (https://cdn.rawgit.com/MathuraMG/p5-accessibility/298ccdf6/dist/p5-accessibility.js:1524:5)
    at e.p5.(anonymous function) [as background] (https://cdn.rawgit.com/MathuraMG/p5-accessibility/298ccdf6/dist/p5-accessibility.js:1658:25)
    at draw (about:srcdoc:55:3)
    at e.redraw (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/p5.min.js:8:27245)
    at e.p5.(anonymous function) [as redraw] (https://cdn.rawgit.com/MathuraMG/p5-accessibility/298ccdf6/dist/p5-accessibility.js:1673:27)
    at e.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/p5.min.js:7:17856)
```
In [this](http://alpha.editor.p5js.org/itsjoel/sketches/S1F9sSvOG) project.

Weirdly, I opened it in an incognito window and its working fine there. Not sure if it's something about being signed in or if it's an addon.

**Comment by itsjoel** [comment] 2018-03-02 23:25
Also, just confirmed it's *not* hardware acceleration causing it.

**Comment by catarak** [comment] 2018-03-02 23:27
cool! i now see this is an error with the accessibility library (https://github.com/MathuraMG/p5-accessibility) which we are in the processing of moving over to the official processing github organization. i'm gonna move this issue over to there.

**Comment by itsjoel** [comment] 2018-03-02 23:29
👍👍👍
Also, in case it helps, it seems to only occur when I'm signed in.
Thanks!

**Comment by catarak** [comment] 2018-03-02 23:30
I think this means that in your Preferences, you have some accessibility features turned on (which maybe you don't want to have? maybe it could be more clear what these do?)

**Comment by itsjoel** [comment] 2018-03-03 00:16
It appears that table-text is the culprit. I don't know when I would have turned them on, but I might have done it accidentally at some point.

**Comment by catarak** [comment] 2018-03-05 16:07
thanks for the info! i’m gonna close this issue since it’s been moved to the accessibility library.

**Closed by catarak** 2018-03-05 16:07 UTC

**Comment by jayjey3** [comment] 2019-04-08 13:33
PROJECT PREVIOUSLY WORKING BUT NOW GETTING ERROR "SCRIPT ERROR LINE:0

ITS RUNS IN FULL SCREEN MODE BUT ANY EDITS GIVES AN ERROR AS ABOVE

**Comment by catarak** [comment] 2019-04-09 19:17
@jayjey3 could you try looking at the accessibility options again? there was a bug a few days ago that was turning them on by default, which would explain why this is coming up again.
