### ISSUE TITLE
BUG: Incorrect loop counting with specific line break

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js-web-editor#741] opened 2018-10-24 05:13 UTC
Compare the two text outputs in the program below (which should be the same). The first is 6, the second 7, depending on whether there is a line break or not. This is incorrect, and does not happen with p5.js outside of the web-editor.

```js
function setup() {
  
  createCanvas(400, 400);
  
  for (var i = 0; i <= 5; i++); i++;
  	
  text(i,20,20);

  for (var j = 0; j <= 5; j++); 
  	j++;
  
  text(j,20,40);
}
```

**Comment by catarak** [comment] 2018-10-24 17:38
thanks for reporting! i think this has to do with the use of the `loop-protect` library (see #698), which needs to be updated. there are hopefully other ways to structure your code to avoid this!

**Comment by dhowe** [comment] 2018-10-25 04:00
of course none of this code is properly-written, but it is still pretty inexplicable to a student as to why this happens, after we've discussed how lines break shouldn't matter

**Comment by catarak** [comment] 2018-10-25 17:53
i hear that! i can add some priority to working on #698.

**Comment by catarak** [comment] 2021-02-10 00:32
closing as a duplicate of #698, but still an issue!

**Closed** 2021-02-10 00:33 UTC
Labels: duplicate, priority:medium, type:bug
