### ISSUE TITLE
sketch works with VSCode but not with the p5.js web editor

### ISSUE THREAD

**Issue by quinton-ashley** [processing/p5.js-web-editor#2113] opened 2023-02-06 15:17 UTC
Hi I have a project that one of my p5.play discord members made. The code I have here works offline but then doesn't work in the p5.js web editor. I would try to debug it myself but the errors produced by the web editor aren't helpful.

I think it's due to a problem with the p5.js web editor. 

<https://editor.p5js.org/quinton-ashley/sketches/wTql2rYQ6>

EDIT:

Using `loadAnimation` in sequence mode doesn't work in the p5.js web editor.

**Comment by davepagurek** [comment] 2023-02-06 15:48
Looks like this is due to the p5 editor renaming images. I haven't found where in the source code this is, but it seems like hardcoded string paths get rewritten while any programmatically generated strings do not, so splicing an empty string into your path like so will work:
```js
chamaAni = loadAni(`chama/chama_0.png${''}`, 2);
```

**Comment by davepagurek** [comment] 2023-02-06 15:51
update: maybe it's this bit? https://github.com/processing/p5.js-web-editor/blob/b3e49dab26417aa1f5492ef08984429a1dc64ef1/client/modules/Preview/EmbedFrame.jsx#L92 I don't have enough context to know why this path rewriting is necessary so I can't comment on what changing this would involve, maybe a maintainer can take a look and offer an opinion?

**Comment by quinton-ashley** [comment] 2023-02-06 16:00
ahh! I see. I was just about to say the list mode usage `loadAnimation`, in which all the images are listed out, does work in the web editor.

Here's my proposed solution for this, instead of editing the user's code (bad practice!) have the p5.js web editor override the p5 loadImage function and in that function swap the user image names for the real path to the file on the server.

**Comment by davepagurek** [comment] 2023-02-06 16:27
Would anyone be able to explain why file URL replacement is necessary when it seems to still load when it doesn't rewrite the URL? I'm not familiar enough with the infrastructure to know what it might be solving but I'd be interested in learning!

**Comment by quinton-ashley** [comment] 2023-02-06 16:46
oh true, that is strange!

**Comment by kjhollen** [comment] 2023-02-06 17:33
I think this is related to (or a duplicate of) #1738 or #771.

For future bugs, please provide a description of the expected vs. actual behavior. Thanks!

**Comment by quinton-ashley** [comment] 2023-02-06 19:26
So this image loading problem has been a known issue for over 4 years and nothing has been done about it :(

**Comment by davepagurek** [comment] 2023-02-06 19:31
Thanks for linking that! It looks like https://github.com/processing/p5.js-web-editor/issues/771 is the same issue, but it's worth mentioning over there that replacing strings in the sketch assumes that you're looking at the full, final URL, so libraries that `loadImage` for you and modify the URL might break under that current system. If that issue is fixed (e.g. by not replacing URLs) then it sounds like the caching issues in https://github.com/processing/p5.js-web-editor/issues/1738 will start happening.

**Comment by quinton-ashley** [comment] 2023-02-06 19:52
@raclim The ability to programmatically make a list of sequenced images is critical for users that want to use p5.js to display multi-file animations, either on their own in p5.js or with p5.play.

Please make fixing this bug a top priority!

**Comment by kjhollen** [comment] 2023-02-06 20:47
Great, thanks for confirming, @davepagurek. I'm going to close this issue as the bug is already well documented elsewhere. We have a big back log and we're working on getting to things as we can. Thanks for your patience @quinton-ashley.

**Closed as not planned by kjhollen** 2023-02-06 20:47 UTC
Labels: Bug

**Comment by quinton-ashley** [comment] 2023-02-06 21:27
Closed as "not planned"???

It's unacceptable that a bug like this could exist in the backlog for over 4 years. If someone demonstrated this type of problem in my code I'd fix it within a day.

I'll wait one week for the fix but then I'm going to start recommending that people should not use the p5.js web editor and will remove the links to it from my website.

**Comment by kjhollen** [comment] 2023-02-06 21:38
Our github repo only provides two options for closing, "completed" and "not planned", and neither quite work here. As I mentioned, this is a duplicate of another bug and the information needed to fix it is already provided there. That bug will stay open. Keeping duplicates open is just more overhead for the maintainers of the project.

I don't think that making threats is in keeping with our code of conduct, @quinton-ashley. I'm sorry you're frustrated—I know how it feels to really need a feature from an open source project but know that the developer may not be able to prioritize it for a while—this happened to me just last week with another project! Still, I don't think this is an appropriate way to talk to a community member.

**Comment by quinton-ashley** [comment] 2023-02-06 21:46
Okay I see. But I wasn't "making a threat", I'm just saying what I'm going to do if the bug is not fixed. I have students trying to use p5.play right now, they're not going to wait very long for this bug to be fixed and I won't either.

**Comment by quinton-ashley** [comment] 2023-02-06 21:52
I think it's not appropriate to waste students' time with a bug that should've been fixed 4 years ago.

**Comment by kjhollen** [comment] 2023-02-06 21:53
Please be more respectful and considerate in your comments.

I have had students type out the names of all files in their animations when teaching p5.play using the web editor and it is a very reasonable work around, though less convenient. I understand if this is not your preference and you choose to pursue other options.

**Comment by quinton-ashley** [comment] 2023-02-06 21:57
With respect, the student had 21 images they wanted to load! Listing them out is not a reasonable workaround for bad code in the editor that replaces file names.

**Comment by davepagurek** [comment] 2023-02-06 22:33
For the workaround, I don't think anyone is suggesting writing out all 21 images, but rather, using backticks instead of quotes for your image URL. While it's not obvious and you'll have to tell your students about it, it will trigger the p5 editor to not replace the string.

**Comment by quinton-ashley** [comment] 2023-02-06 22:40
The student that rediscovered this bug wasted hours of their time. That reflects badly on me because by having a template for the p5.js web editor on my website I'm signaling to people that I trust it. Seeing that the problem has been known about for 4 years is so disappointing. How is that possible? Being upset and confused by that info is a normal reaction. I'm just expressing my opinion. I wasn't name calling or doing any sort of code of conduct violation.

p5.js is not comparable to some indie open source project that someone does in their free time. The Processing Foundation has money. If I'm not mistaken, @kjhollen  and/or @raclim are paid to work on the web editor.

**Comment by quinton-ashley** [comment] 2023-02-06 22:49
I don't want a workaround for this, although the backtick solution is definitely better @davepagurek . But some of my foreign students don't even have a backtick key on their keyboard.

As one of the biggest outside contributors to the p5.js ecosystem, I am simply requesting that priority is given to fixing this bug ASAP and its not placed in the backlog. I want people using p5.play to be able to use the p5.js web editor without any problems.
