### ISSUE TITLE
Editor becoms very slow after 100 lines of code

### ISSUE THREAD

**Issue by Basant-Chahar-2003** [processing/p5.js-web-editor#2916] opened 2024-01-17 16:43 UTC
### What is your operating system?

Windows

### Web browser and version

chrome

### Actual Behavior

the editor becomes very slow after large number of lines , specially after 100 lines.

### Expected Behavior

Editor should be smooth even after 100 lines of code

### Steps:
1. Just write more than 100 lines in online editor.

**Comment by raclim** [comment] 2024-01-17 17:16
Thanks for reporting this! This is a duplicate of an earlier issue, https://github.com/processing/p5.js-web-editor/issues/1392, so I'm going to close this one to organize issues.

**Closed as completed by raclim** 2024-01-17 17:16 UTC
Labels: Bug
