### ISSUE TITLE
Dragging the `Console` is sluggish when browser window is resized to mobile view

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2641] opened 2023-11-27 06:35 UTC
### p5.js version

2.9.3

### What is your operating system?

Mac OS

### Actual Behavior

Dragging the `Console` is sluggish when browser window is resized to mobile view

### Expected Behavior

Dragging the `Console`  should be smooth and not sluggish when browser window is resized to mobile view

### Steps:
1. Open the editor web app
2. Resize the window till it's mobile size
3. Notice dragging of console is not smooth

**Comment by lindapaiste** [comment] 2023-11-27 19:43
I am not sure why this is happening so it may be tricky to debug.  We probably want to play around in the "Profiler" in React dev tools and see if there is anything alarming.

**Comment by lindapaiste** [comment] 2023-11-27 20:27
I found the issue by Googling: https://github.com/tomkp/react-split-pane/issues/30  The problem is that the drag stops when the mouse goes over the `iframe` that renders the sketch.  We are solving this on desktop with an invisible `div` over the sketch.
https://github.com/processing/p5.js-web-editor/blob/f508f52d42364032eba27fefc763fc4f8c409f7d/client/modules/IDE/pages/IDEView.jsx#L194-L197
https://github.com/processing/p5.js-web-editor/blob/f508f52d42364032eba27fefc763fc4f8c409f7d/client/modules/IDE/pages/IDEView.jsx#L155-L163

**Comment by lakshz** [comment] 2023-12-20 16:35
@lindapaiste I want to work on this. Can this be assigned to me?

**Closed as completed** 2023-12-29 20:53 UTC
Labels: Bug
