### ISSUE TITLE
Saved Codes are disappearing for most my students

### ISSUE THREAD

**Issue by monicaaraujopasb** [processing/p5.js-web-editor#1880] opened 2021-06-01 10:45 UTC
In the last week, many of my students have lost their codes hosted in P5.JS web editor. I use it a lot with my students, they are close to finishing the final project and are losing codes all the time. Please take a look at what might be happening... all of them use the school email to log in, these emails have **@pasb.com.br .
Please help... they are very frustrated and I dont know what to do,

**Comment by catarak** [comment] 2021-06-11 19:23
Thanks for reporting @monicaaraujopasb! I'm really sorry you and your students are having that experience. There's unfortunately not a way to figure out why they are losing their projects just from looking at their accounts. Are the sketches crashing? Are you able to figure out any steps to reproduce the issues? As much information as you could provide would be really helpful to figuring out the root cause of the issue. Thank you!

**Comment by kjhollen** [comment] 2021-11-12 19:30
Hi @monicaaraujopasb, I'm sorry that your students had this experience. I am a teacher too and understand how stressful this can be!

I'm going to close this issue because we don't have enough information to do any further debugging, but I think it's possible that there was some trouble with the saving model and we have a few open issues to track this. If you can provide links to specific sketches or accounts that were producing problems, we can reopen this issue and investigate further. Thank you!

**Closed as completed by kjhollen** 2021-11-12 19:30 UTC
