### ISSUE TITLE
Delete sketch fails

### ISSUE THREAD

**Issue by jht9629-nyu** [processing/p5.js-web-editor#3103] opened 2024-04-29 13:24 UTC
### p5.js version

Web Editor: v2.12.9 , p5.js: v1.9.2

### What is your operating system?

Mac OS

### Web browser and version

Version 124.0.6367.62 (Official Build) (arm64)

### Actual Behavior

Delete sketch fails

### Expected Behavior

Sketch to be deleted

### Steps:
1. login to editor.p5js 
2. create a new sketch
3. save it
4. go to my sketches and select delete
5. result : sketch is still in the list

**Comment by raclim** [comment] 2024-04-29 13:34
Thank you so much for reporting this! This seems to have been caused by an earlier fix pushed out last week to mitigate the [consistent outages that were occurring with the editor](https://github.com/processing/p5.js-web-editor/issues/3096#issuecomment-2081530668). I'm hoping to push out a fix for this within the next day or two, and will keep this and the other thread updated as it progresses. I'm sorry that there's been so many issues cropping up over the past week 😅 and thank you again for your patience as they get resolved soon!

**Comment by jht9629-nyu** [comment] 2024-04-29 13:48
I see this error for  delete request in Chrome Network debugger:

> Request URL: https://editor.p5js.org/editor/projects/d_9hVv15K
> Request Method: DELETE
> Status Code: 500 Internal Server Error
> 

response:

> message: "Failed to delete associated project files."}

**Comment by jonfroehlich** [comment] 2024-04-30 11:36
Same here. This is the error I receive when trying to delete a sketch:

```
DELETE https://editor.p5js.org/editor/projects/i5ixkn18g 500 (Internal Server Error)
```

![image](https://github.com/processing/p5.js-web-editor/assets/1621749/f7c33fe1-4c2e-454a-87a7-745711899790)

**Comment by raclim** [comment] 2024-04-30 22:44
I think this should now be addressed with the latest release and pull request (https://github.com/processing/p5.js-web-editor/pull/3107)!! I'm going to close this for now, but please let me know if you're still experiencing issues with this! Thank you so much again for your patience with this!!!

**Closed as completed by raclim** 2024-04-30 22:44 UTC
Labels: Priority:High, Bug

**Comment by jht9629-nyu** [comment] 2024-05-01 04:09
delete function checks out oK!
Verified by [p5mirrorLib crud](https://github.com/molab-itp/p5mirrorLib?tab=readme-ov-file#crud)
