### ISSUE TITLE
Add to collection UI

### ISSUE THREAD

**Issue by amcc** [processing/p5.js-web-editor#2579] opened 2023-11-07 12:07 UTC
### Increasing Access

Currently when adding to a collection you have no indication of whether the sketch is already in a collection or not. The only way of seeing which collection the sketch might already be in is by hovering over each collection and looking for a + or x next to that collection.

This is very hard to use and has not 'at a glance' intuitive understanding of what is happening. A quick look at the HTML seems to indicate that this would be quite hard/impossible for someone using a screen reader. 

### Feature enhancement details

- If a sketch is in a collection have a visual indication that it has already been added. Perhaps colour (p5 pink) and usage of the ✅ mark to indicate that it is added.
- Perhaps use 'known' systems such as checkboxes. These are normally used when showing lists of non-mutually exclusive items that can be added/removed. They would also come with built-in accessibility features.
- Raw tickboxes would work much better than the current system, though they could be styled to fit in with the theme easily

**Comment by lindapaiste** [comment] 2023-11-07 18:52
Possible duplicate of #2255

**Comment by amcc** [comment] 2023-11-07 21:27
Yes it is a duplicate. Didn’t spot that before. Similar solutions have been
proposed

**Comment by raclim** [comment] 2023-11-08 15:45
Since it's a duplicate I'm going to close this one for now to consolidate issues!

**Closed as completed by raclim** 2023-11-08 15:45 UTC
Labels: Enhancement
