### ISSUE TITLE
Problem with splice in web editor

### ISSUE THREAD

**Issue by joemckay5** [processing/p5.js-web-editor#414] opened 2017-08-05 18:46 UTC
Okay, I *think* the problem is with splice; 
This sketch crashes in the editor after a couple seconds throwing the error "Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'. (sketch: line 45) " 
The sketch runs just fine if you export and run it in the browser. 
Twist: if you comment line 31 or 32, so the object is only drawing one element, the sketch doesn't crash.  
Observation: changing the lineSpeed variable will alter how many cycles of splicing it will do before crashing, but it will always crash the same number of times if you don't change the speed. 
I have saved this in my joemckay profile as "crashtest" 

```javascript
var lineList = [];
var count = 0;
var timer; 
var interval = 1000;
function setup() {
  createCanvas(800, 400);
  lineList.push(new LineClass(0));
  timer = millis(); 
}
function draw() {
  background(220);

  if (millis() - timer > interval) { 
    timer = millis();
    lineList.push(new LineClass(0));
  }
  for (var i = 0; i <= lineList.length - 1; i++) {
    lineList[i].display();
    lineList[i].move();
  }
  if (lineList[0].LineY > 50.0) {
    count++;
    print(count);
    lineList.splice(0, 1);
  }
}
function LineClass(_y) {
  this.LineY = _y;
  this.display = function() {
    line(0, this.LineY, width, this.LineY);
    ellipse(20, this.LineY, 20, 20);
  }
  this.move = function() {
    this.lineSpeed = 0.5;
    this.LineY += this.lineSpeed;
  }
}
```

**Comment by catarak** [comment] 2017-08-07 19:46
i think i've seen this error appear without using splice... not sure what's up but it's good to have a starting point

**Comment by joemckay5** [comment] 2017-08-09 15:28
It's definitely something to do with the preview window, and splice is just illuminating the bug. There's no problem when you use the fullscreen link.

**Comment by catarak** [comment] 2017-08-09 20:15
got it. there's some processing that's not happening on the fullscreen view, which is checking for infinite loops so that the whole web editor doesn't crash, and i'll bet that has something to do with it

**Comment by catarak** [comment] 2019-12-11 23:07
closing this issue since it's old and i'm no longer able to reproduce.

**Closed by catarak** 2019-12-11 23:07 UTC
