### ISSUE TITLE
unexpected revert to previous version of file

### ISSUE THREAD

**Issue by lbarron1** [processing/p5.js-web-editor#437] opened 2017-09-13 22:09 UTC
All the code written for a project reverted to an earlier version unexpectedly. The project was saved regularly and no other issues seemed present. The file that the piece went back to was the one saved prior to closing the browser and reopening it to work on it later.

**Comment by catarak** [comment] 2017-09-14 18:24
I've noticed something similar in #419. I will investigate, and if you notice any more specific steps to reproduce add them here!

**Comment by ajuusola** [comment] 2019-03-06 16:18
I'm also having this issue. 
I've been attempting to work in p5 throughout the week, but I keep running into issues where my sketch will revert back to a previous duplicate I have made of it several minutes (sometimes even days) ago. No matter how many times I save, restart my computer/browser, or duplicate my documents, it still decides to jump back to a previous version of the sketch I've been using and erase all of the progress I've made. I ran into this issue last week as well. I tried completely re-imaging my computer (for additional reasons) and using a different browser, but it didn't work.

**Comment by dhruvdutt** [comment] 2019-03-23 13:26
Couldn't reproduce it. @catarak were you able to reproduce it by any chance?

**Comment by catarak** [comment] 2019-03-25 21:24
i'm thinking that this has to do with having multiple versions of the same sketch open.

**Comment by catarak** [comment] 2019-04-17 20:19
just pushed a fix (#1039) that hopefully fixes this!

**Closed** 2019-06-12 21:13 UTC
Labels: priority:high, type:bug
