### ISSUE TITLE
Error message not showing in proper selected language 

### ISSUE THREAD

**Issue by poojadas09** [processing/p5.js-web-editor#3202] opened 2024-08-01 12:11 UTC
### What is your operating system?

Windows

### Web browser and version

127.0.6533.74 (Official Build) (64-bit) (cohort: Control) 

### Actual Behavior

Go to Home page
Change Language to your understandable language
When you don't enter Email and try to login it shows "Please enter email" in English

### Expected Behavior

Go to Home page
Change Language to your understandable language e.g hindi
When you don't enter Email and try to login it shows "Please enter email" in Hindi

### Steps:
Go to Home page
Change Language to your understandable language
When you don't enter Email and try to login it shows "Please enter email" in English
### Snippet:
```js

// Paste your code here :)
![error in p5 editor](https://github.com/user-attachments/assets/dbcf0337-4205-49d0-82c8-3bdf634becb2)


```

**Comment by ajaxonchain** [comment] 2024-08-01 21:33
I would like to work on this issue. Can you assign it to me?

**Comment by raclim** [comment] 2024-08-12 15:38
Thank you for reporting this! 

I've tried to trigger this email error while using different translations, and have not been able to reproduce this particular issue. I think something similar to this might happen if you receive this error message and try to change the language, but it can be adjusted by reloading the page or recreating the error again. 

Looking at the [file that handles this](https://github.com/processing/p5.js-web-editor/blob/41d0303384b4e72887224eff37af99574c813ee0/client/utils/reduxFormUtils.js#L4), it seems that the particular function, `validateLogin`, is handling the translations correctly. Due to this, I personally feel that this is not an issue for now and will close this here. However, I'm open to revisiting this if there are more reports of this in the future, thanks!

**Closed as not planned by raclim** 2024-08-12 15:38 UTC
Labels: Bug
