### ISSUE TITLE
Line 0 error (iOS Only)

### ISSUE THREAD

**Issue by Lawlzer** [processing/p5.js-web-editor#801] opened 2019-01-08 16:55 UTC
#### Nature of issue?

- Found a bug and Existing feature enhancement

#### Details about the bug: Whenever I make an error in the code (bug, error, typo, **anything**), it gives me a weird error: """Script error.  (: line 0)""" and it only happens on iOS, never on Chrome/a computer, and persists after restarting, new program, anything, and has always been this way. 

- Web browser and version:  Safari (same as iPad version apparently, 11.3.1)

- Operating System:  iOS // iPad version 11.3.1
- Steps to reproduce this bug: Make any error in a program, it'll automatically make the same error, no matter what mistake it is.

 console.log(var_that_doesnt_exist) // console.log("hi) // ver x = 0; // etc.
![7f83598b-c5e1-417c-9587-4a00cc157fc5](https://user-images.githubusercontent.com/17093770/50845977-b99f5e80-1333-11e9-868c-132a6b32a885.png)

**Comment by catarak** [comment] 2019-01-09 00:34
thanks for reporting! i'm also able to reproduce this on desktop safari. a lot of changes have been made recently to the console, so i assume it's related to those. will investigate!

**Comment by catarak** [comment] 2021-02-10 17:18
just tested this on an ipad and it seems to be working now! closing 📪

**Closed by catarak** 2021-02-10 17:18 UTC
Labels: help wanted, priority:high, type:bug
