### ISSUE TITLE
fullscreen bugs

### ISSUE THREAD

**Issue by CheetoLord211738** [processing/p5.js-web-editor#1446] opened 2020-06-03 07:04 UTC
Found a bug

Chrome version 83.0.4103.61
Windows 10

Steps to reproduce this bug:
simply change the URL from https://editor.p5js.org/exampleName/sketches/123412345
to https://editor.p5js.org/exampleName/full/123412345

this usually full screens the canvas room, which is useful when working with a large canvas. but recently, it stopped working for me. it simply wouldn't load the project, and put me in a blank p5.js screen.

if you use inspect element, then go to the console log, you get the message:
Failed to load resource: https://editor.p5js.org/editor/undefined/projects/123412345
the server responded with a status of 404 ()

when the link in the error message is clicked, you get a screen that simply says:
{"message":"Project with that username does not exist"}

so i tried replacing the piece that says 'undefined' with my username in the error message link, and the new link took me to a page with my project data.

im not gonna pretend to know why that happens, or how it should work, but these are my findings. thanks in advance for helping.

**Comment by catarak** [comment] 2020-06-03 21:09
Thanks for reporting! I'm going to close this as a duplicate of #1445.

**Closed by catarak** 2020-06-03 21:09 UTC
