### ISSUE TITLE
Chrome 83 download from sandboxed iframes breaks save() functions

### ISSUE THREAD

**Issue by awarua** [processing/p5.js-web-editor#1443] opened 2020-05-29 05:21 UTC
#### Nature of issue?

- Found a bug

#### Details about the bug: 

In Chrome 83, download from sandboxed iframes was removed. This prevents functions such as `image.save()`, `saveCanvas()` or `saveFrames()` from working. According to the Chrome status page below, a flag on the embedded iframe is required to allow this:

[chromestatus.com/feature/5706745674465280](https://www.chromestatus.com/feature/5706745674465280)

- Web browser and version: Google Chrome | 83.0.4103.61 (Official Build) (64-bit)
- Operating System: MacOSX 10.15.4
- Steps to reproduce this bug:

1. Run the following from the 'sketches' or 'full' views of the p5js web editor ([example](https://editor.p5js.org/creativecoding/sketches/9FuK4a5lg)):

```
function setup() {
  createCanvas(400, 400);
  background(255, 0, 0);
  saveCanvas('test', 'png');
}
```

2. In the developer console, you should see the following message:

![image](https://user-images.githubusercontent.com/92529/83224055-dbff7980-a1bf-11ea-94ca-8f1d9d0d7ae2.png)

3. Run the same code in the 'present' mode and it will work ([example](https://editor.p5js.org/creativecoding/present/9FuK4a5lg))

**Comment by Sladix** [comment] 2020-05-29 12:27
Looks like the iframe is missing the `allow-downloads` value in the sandbox attribute

**Comment by catarak** [comment] 2020-05-29 15:09
Thanks for reporting! Hopefully this can be fixed by adding the `allow-downloads` flag.

**Comment by brytlao** [comment] 2020-06-15 01:11
This is still an issue. Will the folks at p5js allow downloads?

**Comment by catarak** [comment] 2020-06-15 17:21
This will be fixed for the next release.

**Closed** 2020-06-15 17:21 UTC
Labels: priority:high, type:bug

**Comment by nnja** [comment] 2020-07-13 05:10
I ran into this issue today as well. Looks like this missed the June 10th release by a few days. Any idea when the next release might be?

I would offer to update the docs for `save`, `saveCanvas`, etc to notify users that this functionality currently doesn't work in chrome but it looks like the docs are tied to the code / release schedule.

**Comment by catarak** [comment] 2020-07-13 15:31
@nnja it will be this week!

**Comment by catarak** [comment] 2020-07-13 20:45
@nnja actually I was able to do a release today, so now this is fixed in production 😄

**Comment by brytlao** [comment] 2020-07-14 00:25
I confirmed that it works. Thank you 😄
