### ISSUE TITLE
Deleted my index.html, and I'm not allowed to make .index files, so my project is in a broken state.

### ISSUE THREAD

**Issue by MyNameIsTrez** [processing/p5.js-web-editor#1212] opened 2019-11-23 21:55 UTC
##### Nature of issue?
- Found a bug & New feature request

#### Details about the bug:
- Deleted my index.html, and I'm not allowed to make .index files, so my project is in a broken state.

- Web browser and version: On Chrome
- Operating System: Windows
- Steps to reproduce this bug:
1. Create a new project.
2. Delete the index.html.
3. When you try to re-add an index.html file, you get the error 'Invalid file type. Valid extensions are .js, .css, .json, .txt, .csv, .tsv, .frag, and .vert.'

#### Feature enhancement details:
Don't allow the user to delete the index.html file, as it'll leave their project in a broken state.

**Comment by catarak** [comment] 2019-11-25 22:41
thanks for reporting! this is currently captured as #1070, so i'm going to close this issue as a duplicate of that one.

**Closed by catarak** 2019-11-25 22:41 UTC
