### ISSUE TITLE
In `About` modal position of "Contribute" and "Report a bug" is not consistent

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2531] opened 2023-10-24 08:35 UTC
### p5.js version

2.8.0

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

In `About` modal position of "Contribute" and "Report a bug" is not consistent

<img width="717" alt="p5-about" src="https://github.com/processing/p5.js-web-editor/assets/47579287/d47d0a83-739e-4914-91bb-0711a4081361">

### Expected Behavior

In `About` modal position of "Contribute" and "Report a bug" should be  consistent

### Steps:
1. Open the editor
2. Go to Help dropdown
3. Click on about 
4. Notice at the end of modal, position of contribute and report a bug is not consistent

**Comment by lindapaiste** [comment] 2023-10-24 14:26
Good catch.  We recently added some responsive breakpoints to that component which are better than nothing but not perfect.  I bet if you look through the git history of the `_about.scss` you can see what we used to have.  I think there was previously a large left margin on the footer section to align it?  We would want to put that back in, but only on large/desktop screens.

**Comment by Shekhar-Dangi** [comment] 2023-10-25 02:37
@lindapaiste I am excited to work on it. May I?

**Comment by bikrantjajware** [comment] 2023-10-25 04:52
Hello, is the expected design something like this. Aligned vertically with above columns
<img width="716" alt="image" src="https://github.com/processing/p5.js-web-editor/assets/34072248/26ce59bc-737f-47cc-ada3-ae0935e38cdd">

**Comment by Ahmed-Armaan** [comment] 2023-10-25 23:13
@PiyushChandra17 hello, is this the desired output, the Contribute and report links alligned with the two existing columns? If yes, I would like to create a pr.
![Screenshot_20231026_0438291](https://github.com/processing/p5.js-web-editor/assets/117345491/32c71db1-ff85-4754-af90-fc77cc52ea02)

**Comment by Swapnil-2502** [comment] 2023-10-27 06:48
@lindapaiste As I can see from history there was a larger left padding at the ".about__footer" so putting that back it would look something like this. Is this what you wanted it to be ?

![Screenshot 2023-10-27 at 12 04 49 PM](https://github.com/processing/p5.js-web-editor/assets/69076366/f253d1c2-9c5d-4ce5-b825-5d8025d3933c)

And also "New to p5.js?" and "Resources" which are column title are also not align to column list, so is that ok then ignore it, I just removed there left padding it looks better for me, if you can comment on them as well.

**Comment by mhsh312** [comment] 2023-10-28 18:46
Greetings, is this the desired result? If so, let me create a PR.
![image](https://github.com/processing/p5.js-web-editor/assets/135870090/3671d309-c009-4e05-b40a-2ddcc97504f6)

**Comment by mhsh312** [comment] 2023-10-28 18:59
Greetings, is this the desired result? If so, let me know so I can make a PR. 
![image](https://github.com/processing/p5.js-web-editor/assets/135870090/f8f73616-7865-40d4-a65f-bcad5b69d943)
If not, please specify how the content should be styled.

**Comment by PiyushThapaa** [comment] 2023-11-06 14:35
I'd like to work on this issue can you assign it to me?

**Comment by yashpandey06** [comment] 2023-11-06 20:37
@PiyushThapaa  I am already working on it !!!!

**Comment by yashpandey06** [comment] 2023-11-06 20:37
@PiyushThapaa  but if you have already done it you can make the pr

**Comment by PiyushThapaa** [comment] 2023-11-07 13:54
> @PiyushThapaa but if you have already done it you can make the pr

no i haven't 
can you please help me
i enable to host the server do you how to host the server locally after cloning

**Comment by yashpandey06** [comment] 2023-11-13 19:02
you can simply use docker setup to start a localhost ...go through the contributing docs

**Comment by yashpandey06** [comment] 2023-11-13 19:07
@PiyushChandra17  I am going to raise pr for this particular issue soon ...but firstly let me know if you are working on this issue.

**Comment by udittripathi** [comment] 2023-11-20 05:26
I can host the application locally using docker but when I make changes in the code it is not getting refreshed in the code. So I have to build a new image every time there is something I am doing wrong. Kindly help me with this.

**Comment by shree6** [comment] 2023-11-25 07:09
Is this still open? Can i work on it?

**Comment by shree6** [comment] 2023-11-25 10:18
@udittripathi
Same problem has been there for me.

**Comment by udittripathi** [comment] 2023-11-25 10:55
@shree6 If you find the solution please le me know also

**Comment by udittripathi** [comment] 2023-11-27 11:30
@lindapaiste can u help me with this issue?

**Comment by Saikat123Dev** [comment] 2023-12-18 11:04
![Screenshot from 2023-12-18 15-29-40](https://github.com/processing/p5.js-web-editor/assets/149571282/c02bdf72-3c5a-4036-9127-dd32b6268408)
![Uploading Screenshot from 2023-12-18 15-29-40.png…]()

**Comment by Saikat123Dev** [comment] 2023-12-18 11:06
![Screenshot from 2023-12-18 15-30-15](https://github.com/processing/p5.js-web-editor/assets/149571282/15b455f6-bdfc-4467-868c-305d50595d57)

**Comment by shamvrueth** [comment] 2024-01-22 14:40
@lindapaiste If the issue is still not resolved, can I work on it?

**Comment by raclim** [comment] 2024-08-13 16:05
Closing to organize and conslidate issues, linked in Megathread.

**Closed as not planned by raclim** 2024-08-13 16:05 UTC
Labels: Area: Design, Bug
