### ISSUE TITLE
Failed to upload files with non-English names

### ISSUE THREAD

**Issue by oneandzeros** [processing/p5.js-web-editor#1620] opened 2020-09-23 05:56 UTC
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: chrome 85.0.4183.121
- Operating System: windows 10 pro
- Steps to reproduce this bug:

I was trying to upload a png file with name "图片.png" , the uploading process is OK, but picture does not show in the Sketch files list .

I rename it with "tmp.png", reprocess the uploading and it worked. <It took a long time for to find this way>

This is how I did it：
![p5jsbug](https://user-images.githubusercontent.com/12198564/93971763-7f921c80-fda3-11ea-8421-827cc7a00614.gif)
 
Another thing is that I tested a file with name "思维导图笔记.html" , and it worked!

I think only some of the none-Engish names would fail, not all.

Please check.

**Comment by catarak** [comment] 2020-09-23 18:48
Thanks for reporting! I would like for the web editor to support non-English file names, and thanks for submitting some examples of filenames that work and don't work.

**Comment by oneandzeros** [comment] 2020-09-24 08:26
> Thanks for reporting! I would like for the web editor to support non-English file names, and thanks for submitting some examples of filenames that work and don't work.

works:
图片.html
思维导图笔记.html
878世界.html

not work:
图片.png
文本21.gif
878世界.gif
新球大战.gif
这里是地球.gif
코딩을.png


I think all the html files works.  Only pictures have this problem?

**Comment by catarak** [comment] 2020-09-24 16:00
That's super helpful! The way that text files versus images/videos/fonts/etc. are uploaded is different. Text files are uploaded directly to the web editor, whereas other files are uploaded to an Amazon S3 bucket.

**Comment by adarzh-sys** [comment] 2020-09-29 17:10
Hey! First timer here, I would love to help with this issue, any help on how exactly I should proceed would be really helpful :)

**Comment by catarak** [comment] 2020-09-29 17:38
Hi @adarsh-qclw! The first step is getting the web editor running locally on your computer. Then, once that is working, the component that handles the file uploading is [FileUploader.jsx](https://github.com/processing/p5.js-web-editor/blob/develop/client/modules/IDE/components/FileUploader.jsx), and from that component can see all of the functions/API requests that are being made to upload a file, and hopefully figure out what's going wrong.

**Comment by adarzh-sys** [comment] 2020-09-30 04:03
Thanks @catarak ! Is this probably an issue due to encoding not being UTF-8 ?

**Comment by catarak** [comment] 2020-09-30 14:18
@adarsh-qclw I think that is a great guess 😄 I would suggest testing and confirming that!

**Comment by adarzh-sys** [comment] 2020-10-02 06:18
Hey, I'm afraid I'm stuck here. How do I test out my change? Because, in order to try uploading, I need to sign in, which I am unable to, in my local environment. Help? I am a total beginner, please pardon my frequent doubts :")

**Comment by catarak** [comment] 2020-10-06 18:17
In local development, you're using a database that doesn't have your login information that you have on the production web editor, and you'll need to create a new account. This account is only for local testing and none of your sketches will be public.

**Comment by ricknjacky** [comment] 2020-10-08 05:37
@catarak can I work on this issue? as there have been no recent follow ups

**Comment by catarak** [comment] 2020-10-08 17:28
@ricknjacky for sure! it seems like @adarsh-qclw is stuck but please update if that's not true

**Comment by ricknjacky** [comment] 2020-10-08 17:29
@adarsh-qclw are you working on this ? if not please let us know

**Comment by adarzh-sys** [comment] 2020-10-09 12:34
hey @ricknjacky, you can certainly work on it, i am stuck with a few complications. i would also love to learn how you solved it! cheers :")

**Comment by vulongphan** [comment] 2020-11-06 14:05
@catarak hi I am new to open source in general and to p5 web editor in particular but I want to make an attempt at this good first issue. I have been able to login to the local development with my Github account so I can test out the change. I see no follow ups for a month so  @ricknjacky can you provide some update? If you would like another person to work on this issue I can. Thank you!

**Comment by catarak** [comment] 2020-11-06 20:16
@vulongphan you can go ahead and work on it!

**Comment by vulongphan** [comment] 2020-11-07 15:53
I have been able to reproduce the bug in local development and I just want to point out some things if someone also wants to reproduce the issue:
- To be able to upload the image you need an amazon s3 bucket, follow this [link](https://aws.amazon.com/s3/)
- Update the value of `S3_BUCKET_URL_BASE` in `.env` file, the convention for finding the url can be found [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html)
- Make your bucket publicly accessible (this is not the best practice for sure but this is just for the purpose of reproducing the bug)
- Next edit the CORS policy to add `localhost:8000` as the access origin by pasting in the script:
`
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "http://localhost:8000"
        ],
        "ExposeHeaders": []
    }
]`

**Comment by vulongphan** [comment] 2020-11-08 08:39
I have been able to add files with non-English names, as shown in the attached below.

![2020-11-08 12-13-45](https://user-images.githubusercontent.com/46087559/98460285-8b536a00-21bc-11eb-9e19-889564f24ac5.gif)

So the issue is with the `window.btoa()` function which takes a binary string as an input (a binary string is a string in which each character occupies only one byte). However, for non-English strings, each character occupies more than one byte hence the input string will cause the error `Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`. I solved this by using the `toBinary()` function which converts the input string to a proper format that can be passed into the function. This function and more on how `window.btoa()` deals with input string can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa).

I believe the next step I need to test my change using `npm test` according to the [contributing document](https://github.com/processing/p5.js-web-editor/blob/develop/developer_docs/development.md) but I receive an error which is not caused by my change. This is a screenshot of the testing error

![Screen Shot 2020-11-08 at 12 35 49 PM](https://user-images.githubusercontent.com/46087559/98460563-f1d98780-21be-11eb-8515-4157f45f3744.png)

@catarak Could you please give me some advice in order to move forward?

**Comment by catarak** [comment] 2020-11-09 20:52
@vulongphan would you mind opening a pull request? You could make it a draft one so it's clear it's not ready to be merged. That would help me to help you figure out the issue!

**Comment by vulongphan** [comment] 2020-11-10 12:00
Hi @catarak , I have created a draft pull request. However I am running into this problem: when I run `git rebase upstream/develop` I got `Current branch non_English_filenames is up to date`, but my forked version says it is 47 commits behind the `processing:develop` branch. Do you have any suggestions so that I can solve it?

**Comment by catarak** [comment] 2020-11-12 21:43
I would suggest trying merging rather than rebasing?

**Comment by vulongphan** [comment] 2020-11-13 16:15
@catarak Through the experience with solving this issue, I have a question regarding the contribution to Processing/p5-web-editor:
So the forked version of the p5-web-editor has some errors regarding the `PropTypes` on my local machine. Hence, in order to run the program I need to make some changes (i.e: change the `Proptypes`), let it be A. Then to solve the issue (i.e: [Issue #1620](https://github.com/processing/p5.js-web-editor/issues/1620)), I need to make some other changes (i.e: add function `toBinary()`), let it be B. But to make a PR that fixes the Issue, I need to commit a version that only has changes B (otherwise, as you said I would have too many commits ahead). I think this is very inconvenient for me: in order to test out your PR (i.e: [PR#1672](https://github.com/processing/p5.js-web-editor/pull/1672)), I will have to switch to your feature branch and then apply changes A in order to run my program and see if the PR works.

Do you have any suggestions for me to get around this?

Thank you!

**Comment by catarak** [comment] 2020-11-13 16:54
I think the reason you're seeing all of the `PropTypes` errors is because you're using a different version of Node/React/etc. In the installation instructions it says to use Node version `12.16.1`. I don't know why this happened, but it seems like when you ran `npm install`, it upgraded the minor/patch versions of the libraries (I see the changes in `package.json` and `package-lock.json`. I think if you get rid of those changes, then it will be much smoother!

**Comment by vulongphan** [comment] 2020-11-14 09:13
Hi @catarak, I have been able to switch to Node v `12.16.1` and when I switch to branch `bug/non-english-names` it works well for me and I can see the change in the file uploading. This will definitely help me a lot in the long run. 

Thank you so much for your help! So should we close this issue?

**Comment by catarak** [comment] 2020-11-16 17:41
@vulongphan this issue will automatically close when I merge #1672! Thanks for all of your help on this.

**Closed as completed** 2020-11-16 17:54 UTC
Labels: Help Wanted, Priority:High, Good First Issue
