### ISSUE TITLE
After using the push() function, the previous values cannot be seen

### ISSUE THREAD

**Issue by sahintelli** [processing/p5.js-web-editor#1913] opened 2021-08-08 17:03 UTC
#### Nature of issue?

- Found a bug (perhaps)

#### Details about the bug: 

- Web browser and version: FireFox/Edge
- Operating System: Windows
- Steps to reproduce this bug:

I tried the code provided on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push. However, on https://editor.p5js.org/, it returns a different and an unexpected result for the **_push()_** function. The array is updated but the previous version is also changed. I am unable to see the original array anymore. I would be so happy if anyone could clarify the issue. Thanks 😊✌

![image](https://user-images.githubusercontent.com/36115381/128639613-9abf7efb-fef9-4572-95be-0ed52642a1ba.png)

**Comment by KKVANONYMOUS** [comment] 2021-08-20 15:46
@catarak I want to work on this issue. Would you please guide me on where to look regarding this issue?

**Comment by catarak** [comment] 2021-09-13 22:15
Thanks for reporting! This is a duplicate of #1203, therefore i'm going to close it.

**Closed as completed by catarak** 2021-09-13 22:15 UTC
