### ISSUE TITLE
P5.js Web Editor is not working on Safari. Its downloaded version is not working on PC too.

### ISSUE THREAD

**Issue by yesanpark** [processing/p5.js-web-editor#1878] opened 2021-05-30 09:45 UTC
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by catarak** [comment] 2021-06-01 21:17
Thank you for reporting! I'm unfortunately not able to reproduce—it's working on Safari for me! Can you add information like your operating system, or specific things you can't get to work in the web editor? Thank you!

**Comment by abrennec** [comment] 2021-06-09 12:53
Hi, I have come across the same issue today. p5.js Editor was not working in safari with the default example. When executing / running play button, "Loading ..." occurs and that's it. However, older examples are working. I looked into index.html file and changed the version of p5.sound.min.js. Now things are working again but this is still weird. Could you check again whether you can reproduce, @catarak ? Many thanks!

This combination works for me,
 <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.1/p5.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/addons/p5.sound.min.js"></script>

This combination does not work for me,
 <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.1/p5.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.1/addons/p5.sound.min.js"></script>

**Comment by catarak** [comment] 2021-06-11 16:01
I just re-read the subject of this issue, that the sketch is also not working in Safari when you download the sketch and run it outside of the web editor. This to me implies that the bug is with p5.sound and not the p5.js web editor. That being said, because it is causing issues in the web editor, maybe the solution is changing the default version of p5.js sound. Because I cannot reproduce this issue (because I can't run the version of Safari that causes this bug), @abrennec are you able to figure out the latest version of p5.sound that doesn't break? I recommend looking through the [list of release numbers](https://github.com/processing/p5.js/releases) and going back until you find one that works. Thank you!

**Comment by catarak** [comment] 2021-06-14 19:49
Just pushed a release ([v1.4.1](https://github.com/processing/p5.js-web-editor/releases/tag/v1.4.1)) that fixes this, closing!

**Closed as completed by catarak** 2021-06-14 19:49 UTC

**Comment by abrennec** [comment] 2021-06-14 19:51
Great, many thanks!
