### ISSUE TITLE
Weird JavaScript Behavior

### ISSUE THREAD

**Issue by wowkster** [processing/p5.js-web-editor#1517] opened 2020-07-27 02:58 UTC
#### Nature of issue?
Strange JavaScript behavior only observed in the p5js web editor

- Found a bug

#### Details about the bug: 

- Web browser and version: Microsoft Edge Version: 84.0.522.44 (JavaScript Version: V8 8.4.371.19)
- Operating System: Windows 10 x64
- Steps to reproduce this bug: In the p5js web editor type in the following code:

```javascript
function setup() {
  
  let arr = [5, 4, 3, 2, 1];
  console.log(arr);
  
  arr[0] = 6;
  console.log(arr);
  
}
```
It prints the same thing twice ([6, 4, 3, 2, 1, ]), even though if you type the same code into the JavaScript console, it produces a different result ([5, 4, 3, 2, 1] and then [6, 4, 3, 2, 1]). Because of the way the editor is coded, when running the program, it even prints the correct values to the edge JavaScript console while printing the wrong values to the p5 console.

![image](https://user-images.githubusercontent.com/49880655/88499356-937ff480-cf93-11ea-880f-c3fe8af9e7d1.png)

Edit: I also noticed that if you change the code to only print the first element of the array, then it works as expected:
```javascript
function setup() {
  
  let arr = [5, 4, 3, 2, 1];
  console.log(arr[0]);
  
  arr[0] = 6;
  console.log(arr[0]);
  
}
```
![image](https://user-images.githubusercontent.com/49880655/88499520-16a14a80-cf94-11ea-8e50-5f646e1a5e77.png)

Edit 2: While doing some more experimentation with arrays in the editor, I also found that a similar thing happens with the push() method:
```javascript
function setup() {
  let fruits = ["Banana", "Orange", "Apple", "Mango"];
  console.log(fruits);
  
  fruits.push("Lemon"); // adds a new element (Lemon) to fruits
  console.log(fruits);
}
```
![image](https://user-images.githubusercontent.com/49880655/88499802-f58d2980-cf94-11ea-9905-17a8681dc719.png)

**Comment by Guillaume57** [comment] 2020-07-27 03:29
Hello,

Yes, it's a known issue but has nothing to do with p5.js, basically it's because console.log is asynchronous. If you replace it with alert() you will see correct result, but if you want to use console.log you will have to print a copy of the array
```
function setup() {
  
  let arr = [5, 4, 3, 2, 1];
  console.log(Array.from(arr));
  
  arr[0] = 6;
  console.log(arr);
  
}
```

**Comment by catarak** [comment] 2020-07-27 17:04
Thanks for reporting! This is a duplicate of #1203 I think.

**Closed** 2020-07-27 17:05 UTC
Labels: duplicate
